(function(a){a.build={version:"2.1.1.42",closureCompiled:!0,bundled:!1,imgrecvServer:"http://featherservices.aviary.com/FeatherReceiver.aspx",imgrecvServer_SSL:"https://featherservices.aviary.com/FeatherReceiver.aspx",inAppPurchaseFrameURL:"http://purchases.viary.com/gateway.aspx?p=flickr",imgrecvBase:"http://featherservices.aviary.com/",imgrecvBase_SSL:"https://featherservices.aviary.com/",imgtrackServer:"http://featherservices.aviary.com/featherlog.aspx",imgtrackServer_SSL:"https://featherservices.aviary.com/featherlog.aspx",
filterServer:"http://featherservices.aviary.com/moa.ashx",filterServer_SSL:"https://featherservices.aviary.com/moa.ashx",flashGatewayServer:"http://featherservices.aviary.com/gateway.aspx",flashGatewayServer_SSL:"https://featherservices.aviary.com/gateway.aspx",jsonp_imgserver:"http://featherservices.aviary.com/imgjsonpserver.aspx",jsonp_imgserver_SSL:"https://featherservices.aviary.com/imgjsonpserver.aspx",featherTargetAnnounce:"http://featherservices.aviary.com/feather_target_announce.html",featherTargetAnnounce_SSL:"https://featherservices.aviary.com/feather_target_announce.html",
featherFilterAnnounce:"http://featherservices.aviary.com/feather_filter_announce.html",featherFilterAnnounce_SSL:"https://featherservices.aviary.com/feather_filter_announce.html",proxyServer:"http://featherservices.aviary.com/proxy.aspx",proxyServer_SSL:"https://featherservices.aviary.com/proxy.aspx",feather_baseURL:"http://feather.aviary.com/2.1.1.42/",feather_baseURL_SSL:"https://dme0ih8comzn4.cloudfront.net/2.1.1.42/",feather_stickerURL:"http://feather.aviary.com/stickers/",feather_stickerURL_SSL:"https://dme0ih8comzn4.cloudfront.net/stickers/",
googleTracker:"UA-84575-16"}})(AV=window.AV||{});var avpw_swfobject=function(){function a(){if(!E){try{var a=o.getElementsByTagName("body")[0].appendChild(o.createElement("span"));a.parentNode.removeChild(a)}catch(c){return}E=!0;for(var a=H.length,f=0;f<a;f++)H[f]()}}function d(a){E?a():H[H.length]=a}function c(a){if(typeof A.addEventListener!=q)A.addEventListener("load",a,!1);else if(typeof o.addEventListener!=q)o.addEventListener("load",a,!1);else if(typeof A.attachEvent!=q)u(A,"onload",a);else if("function"==typeof A.onload){var c=A.onload;A.onload=
function(){c();a()}}else A.onload=a}function e(){var a=o.getElementsByTagName("body")[0],c=o.createElement(y);c.setAttribute("type",I);var e=a.appendChild(c);if(e){var d=0;(function(){if(typeof e.GetVariable!=q){var i=e.GetVariable("$version");i&&(i=i.split(" ")[1].split(","),l.pv=[parseInt(i[0],10),parseInt(i[1],10),parseInt(i[2],10)])}else if(10>d){d++;setTimeout(arguments.callee,10);return}a.removeChild(c);e=null;f()})()}else f()}function f(){var a=C.length;if(0<a)for(var c=0;c<a;c++){var f=C[c].id,
e=C[c].callbackFn,d={success:!1,id:f};if(0<l.pv[0]){var m=p(f);if(m)if(z(C[c].swfVersion)&&!(l.wk&&312>l.wk))w(f,!0),e&&(d.success=!0,d.ref=h(f),e(d));else if(C[c].expressInstall&&i()){d={};d.data=C[c].expressInstall;d.width=m.getAttribute("width")||"0";d.height=m.getAttribute("height")||"0";m.getAttribute("class")&&(d.styleclass=m.getAttribute("class"));m.getAttribute("align")&&(d.align=m.getAttribute("align"));for(var v={},m=m.getElementsByTagName("param"),s=m.length,x=0;x<s;x++)"movie"!=m[x].getAttribute("name").toLowerCase()&&
(v[m[x].getAttribute("name")]=m[x].getAttribute("value"));k(d,v,f,e)}else j(m),e&&e(d)}else if(w(f,!0),e){if((f=h(f))&&typeof f.SetVariable!=q)d.success=!0,d.ref=f;e(d)}}}function h(a){var c=null;if((a=p(a))&&"OBJECT"==a.nodeName)typeof a.SetVariable!=q?c=a:(a=a.getElementsByTagName(y)[0])&&(c=a);return c}function i(){return!J&&z("6.0.65")&&(l.win||l.mac)&&!(l.wk&&312>l.wk)}function k(a,c,f,d){J=!0;M=d||null;O={success:!1,id:f};var e=p(f);if(e){"OBJECT"==e.nodeName?(G=n(e),K=null):(G=e,K=f);a.id=
P;if(typeof a.width==q||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if(typeof a.height==q||!/%$/.test(a.height)&&137>parseInt(a.height,10))a.height="137";o.title=o.title.slice(0,47)+" - Flash Player Installation";d=l.ie&&l.win?"ActiveX":"PlugIn";d="MMredirectURL="+encodeURI(window.location).toString().replace(/&/g,"%26")+"&MMplayerType="+d+"&MMdoctitle="+o.title;c.flashvars=typeof c.flashvars!=q?c.flashvars+("&"+d):d;l.ie&&(l.win&&4!=e.readyState)&&(d=o.createElement("div"),f+="SWFObjectNew",
d.setAttribute("id",f),e.parentNode.insertBefore(d,e),e.style.display="none",function(){e.readyState==4?e.parentNode.removeChild(e):setTimeout(arguments.callee,10)}());m(a,c,f)}}function j(a){if(l.ie&&l.win&&4!=a.readyState){var c=o.createElement("div");a.parentNode.insertBefore(c,a);c.parentNode.replaceChild(n(a),c);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(n(a),a)}function n(a){var c=o.createElement("div");
if(l.win&&l.ie)c.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(y)[0])if(a=a.childNodes)for(var f=a.length,d=0;d<f;d++)!(1==a[d].nodeType&&"PARAM"==a[d].nodeName)&&8!=a[d].nodeType&&c.appendChild(a[d].cloneNode(!0));return c}function m(a,c,f){var d,e=p(f);if(l.wk&&312>l.wk)return d;if(e)if(typeof a.id==q&&(a.id=f),l.ie&&l.win){var i="",h;for(h in a)a[h]!=Object.prototype[h]&&("data"==h.toLowerCase()?c.movie=a[h]:"styleclass"==h.toLowerCase()?i+=' class="'+a[h]+'"':"classid"!=h.toLowerCase()&&
(i+=" "+h+'="'+a[h]+'"'));h="";for(var k in c)c[k]!=Object.prototype[k]&&(h+='<param name="'+k+'" value="'+c[k]+'" />');e.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+i+">"+h+"</object>";L[L.length]=a.id;d=p(a.id)}else{k=o.createElement(y);k.setAttribute("type",I);for(var m in a)a[m]!=Object.prototype[m]&&("styleclass"==m.toLowerCase()?k.setAttribute("class",a[m]):"classid"!=m.toLowerCase()&&k.setAttribute(m,a[m]));for(i in c)c[i]!=Object.prototype[i]&&"movie"!=i.toLowerCase()&&
(a=k,h=i,m=c[i],f=o.createElement("param"),f.setAttribute("name",h),f.setAttribute("value",m),a.appendChild(f));e.parentNode.replaceChild(k,e);d=k}return d}function s(a){var c=p(a);c&&"OBJECT"==c.nodeName&&(l.ie&&l.win?(c.style.display="none",function(){if(4==c.readyState){var f=p(a);if(f){for(var d in f)"function"==typeof f[d]&&(f[d]=null);f.parentNode.removeChild(f)}}else setTimeout(arguments.callee,10)}()):c.parentNode.removeChild(c))}function p(a){var c=null;try{c=o.getElementById(a)}catch(f){}return c}
function u(a,c,f){a.attachEvent(c,f);F[F.length]=[a,c,f]}function z(a){var c=l.pv,a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return c[0]>a[0]||c[0]==a[0]&&c[1]>a[1]||c[0]==a[0]&&c[1]==a[1]&&c[2]>=a[2]?!0:!1}function x(a,c,f,d){if(!l.ie||!l.mac){var e=o.getElementsByTagName("head")[0];if(e){f=f&&"string"==typeof f?f:"screen";d&&(N=B=null);if(!B||N!=f)d=o.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",f),B=e.appendChild(d),
l.ie&&(l.win&&typeof o.styleSheets!=q&&0<o.styleSheets.length)&&(B=o.styleSheets[o.styleSheets.length-1]),N=f;l.ie&&l.win?B&&typeof B.addRule==y&&B.addRule(a,c):B&&typeof o.createTextNode!=q&&B.appendChild(o.createTextNode(a+" {"+c+"}"))}}}function w(a,c){if(Q){var f=c?"visible":"hidden";E&&p(a)?p(a).style.visibility=f:x("#"+a,"visibility:"+f)}}function v(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=q?encodeURIComponent(a):a}var q="undefined",y="object",I="application/x-shockwave-flash",
P="SWFObjectExprInst",A=window,o=document,D=navigator,R=!1,H=[function(){R?e():f()}],C=[],L=[],F=[],G,K,M,O,E=!1,J=!1,B,N,Q=!0,l=function(){var a=typeof o.getElementById!=q&&typeof o.getElementsByTagName!=q&&typeof o.createElement!=q,c=D.userAgent.toLowerCase(),f=D.platform.toLowerCase(),d=f?/win/.test(f):/win/.test(c),f=f?/mac/.test(f):/mac/.test(c),c=/webkit/.test(c)?parseFloat(c.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,e=!+"\v1",i=[0,0,0],h=null;if(typeof D.plugins!=q&&typeof D.plugins["Shockwave Flash"]==
y){if((h=D.plugins["Shockwave Flash"].description)&&!(typeof D.mimeTypes!=q&&D.mimeTypes[I]&&!D.mimeTypes[I].enabledPlugin))R=!0,e=!1,h=h.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),i[0]=parseInt(h.replace(/^(.*)\..*$/,"$1"),10),i[1]=parseInt(h.replace(/^.*\.(.*)\s.*$/,"$1"),10),i[2]=/[a-zA-Z]/.test(h)?parseInt(h.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof A.ActiveXObject!=q)try{var k=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(k&&(h=k.GetVariable("$version")))e=!0,h=h.split(" ")[1].split(","),
i=[parseInt(h[0],10),parseInt(h[1],10),parseInt(h[2],10)]}catch(m){}return{w3:a,pv:i,wk:c,ie:e,win:d,mac:f}}();(function(){l.w3&&((typeof o.readyState!=q&&"complete"==o.readyState||typeof o.readyState==q&&(o.getElementsByTagName("body")[0]||o.body))&&a(),E||(typeof o.addEventListener!=q&&o.addEventListener("DOMContentLoaded",a,!1),l.ie&&l.win&&(o.attachEvent("onreadystatechange",function(){"complete"==o.readyState&&(o.detachEvent("onreadystatechange",arguments.callee),a())}),A==top&&function(){if(!E){try{o.documentElement.doScroll("left")}catch(c){setTimeout(arguments.callee,
0);return}a()}}()),l.wk&&function(){E||(/loaded|complete/.test(o.readyState)?a():setTimeout(arguments.callee,0))}(),c(a)))})();(function(){l.ie&&l.win&&window.attachEvent("onunload",function(){for(var a=F.length,c=0;c<a;c++)F[c][0].detachEvent(F[c][1],F[c][2]);a=L.length;for(c=0;c<a;c++)s(L[c]);for(var f in l)l[f]=null;l=null;for(var d in avpw_swfobject)avpw_swfobject[d]=null;avpw_swfobject=null})})();return{registerObject:function(a,c,f,d){if(l.w3&&a&&c){var e={};e.id=a;e.swfVersion=c;e.expressInstall=
f;e.callbackFn=d;C[C.length]=e;w(a,!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(l.w3)return h(a)},embedSWF:function(a,c,f,e,h,j,v,x,s,p){var n={success:!1,id:c};l.w3&&!(l.wk&&312>l.wk)&&a&&c&&f&&e&&h?(w(c,!1),d(function(){f+="";e+="";var d={};if(s&&typeof s===y)for(var l in s)d[l]=s[l];d.data=a;d.width=f;d.height=e;l={};if(x&&typeof x===y)for(var o in x)l[o]=x[o];if(v&&typeof v===y)for(var u in v)l.flashvars=typeof l.flashvars!=q?l.flashvars+("&"+u+"="+v[u]):u+"="+v[u];if(z(h))o=
m(d,l,c),d.id==c&&w(c,!0),n.success=!0,n.ref=o;else{if(j&&i()){d.data=j;k(d,l,c,p);return}w(c,!0)}p&&p(n)})):p&&p(n)},switchOffAutoHideShow:function(){Q=!1},ua:l,getFlashPlayerVersion:function(){return{major:l.pv[0],minor:l.pv[1],release:l.pv[2]}},hasFlashPlayerVersion:z,createSWF:function(a,c,f){if(l.w3)return m(a,c,f)},showExpressInstall:function(a,c,f,d){l.w3&&i()&&k(a,c,f,d)},removeSWF:function(a){l.w3&&s(a)},createCSS:function(a,c,f,d){l.w3&&x(a,c,f,d)},addDomLoadEvent:d,addLoadEvent:c,getQueryParamValue:function(a){var c=
o.location.search||o.location.hash;if(c){/\?/.test(c)&&(c=c.split("?")[1]);if(null==a)return v(c);for(var c=c.split("&"),f=0;f<c.length;f++)if(c[f].substring(0,c[f].indexOf("="))==a)return v(c[f].substring(c[f].indexOf("=")+1))}return""},expressInstallCallback:function(){if(J){var a=p(P);a&&G&&(a.parentNode.replaceChild(G,a),K&&(w(K,!0),l.ie&&l.win&&(G.style.display="block")),M&&M(O));J=!1}}}}();"undefined"===typeof AV&&(AV={});
AV.FlashAPI=function(){var a=null,d=function(){return function(a,c,d,e,j){var j=j||{},n={quality:"high",bgcolor:"#808080",allowscriptaccess:"always",allowfullscreen:"true"},m={};m.id=a;m.name=a;AV.msie&&9>AV.msie&&(m.align="center");var s=a+"Content",p=j,j={};if(m&&"object"===typeof m)for(var u in m)j[u]=m[u];j.data=c||a+".swf";j.width=(d||"100%")+"";j.height=(e||"100%")+"";a={};if(n&&"object"===typeof n)for(var z in n)a[z]=n[z];if(p&&"object"===typeof p)for(var x in p)a.flashvars="undefined"!=typeof a.flashvars?
a.flashvars+("&"+x+"="+p[x]):x+"="+p[x];if(n=document.getElementById(s))if("undefined"==typeof j.id&&(j.id=s),AV.msie){var w="",v;for(v in j)j[v]!=Object.prototype[v]&&("data"==v.toLowerCase()?a.movie=j[v]:"styleclass"==v.toLowerCase()?w+=' class="'+j[v]+'"':"classid"!=v.toLowerCase()&&(w+=" "+v+'="'+j[v]+'"'));v="";for(var q in a)a[q]!=Object.prototype[q]&&(v+='<param name="'+q+'" value="'+a[q]+'" />');n.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+w+">"+v+"</object>";
"undefined"==typeof objIdArr&&(objIdArr=[]);objIdArr[objIdArr.length]=j.id}else{q=document.createElement("object");q.setAttribute("type","application/x-shockwave-flash");for(var y in j)j[y]!=Object.prototype[y]&&("styleclass"==y.toLowerCase()?q.setAttribute("class",j[y]):"classid"!=y.toLowerCase()&&q.setAttribute(y,j[y]));for(w in a)a[w]!=Object.prototype[w]&&"movie"!=w.toLowerCase()&&(j=q,v=w,y=a[w],s=document.createElement("param"),s.setAttribute("name",v),s.setAttribute("value",y),j.appendChild(s));
n.parentNode.replaceChild(q,n)}}}(),c=function(){};c.prototype=function(){return{getPlugins:function(){return[]},createCanvas:function(){this.initsize?d("canvas",AV.build.feather_baseURL+"canvas.swf",this.initsize.width,this.initsize.height):d("canvas",AV.build.feather_baseURL+"canvas.swf");d("avpw_flashThumb1",AV.build.feather_baseURL+"Thumb.swf","64px","64px",{callback:"AV.FlashAPI.onThumbClick",uid:"avpw_flashThumb1"});d("avpw_flashThumb2",AV.build.feather_baseURL+"Thumb.swf","64px","64px",{callback:"AV.FlashAPI.onThumbClick",
uid:"avpw_flashThumb2"});d("avpw_flashThumb3",AV.build.feather_baseURL+"Thumb.swf","64px","64px",{callback:"AV.FlashAPI.onThumbClick",uid:"avpw_flashThumb3"});d("avpw_flashThumb4",AV.build.feather_baseURL+"Thumb.swf","64px","64px",{callback:"AV.FlashAPI.onThumbClick",uid:"avpw_flashThumb4"})},onSave:function(a){return this.onEndEditing(a)},onEndEditing:function(a){a.commit(AV.FlashAPI.constants.UPLOAD_TO_AVIARY,{url:"http://test.viary.com/apps/xmlapi/receiver.aspx?auid=aviaryframework",name:"image2"})},
onCommitComplete:function(a){AV.controlsWidget_onImageSaved(a.url,a.hiresurl)},_onComponentLoaded:function(a){switch(a){case "canvas":a=document.getElementById(a),AV.FlashAPI._onCanvasLoaded(a)}},_onComponentReady:function(a){if("canvas"===a)for(var c in AV.controlsWidgetInstance.activeTools)if(a=AV.controlsWidgetInstance.activeTools[c],!AV.paintWidgetInstance.moduleHasLoaded[a]&&AV.toolDefaults[a]&&AV.toolDefaults[a].files)AV.paintWidgetInstance.onModuleLoaded(a)}}}();var e={listenerList:{},addListener:function(a,
c){this.listenerList.hasOwnProperty(a)||(this.listenerList[a]=[]);this.listenerList[a].push(c)},removeAllListeners:function(){this.listenerList={}},doCallbacks:function(a){var c,d;if(this.listenerList.hasOwnProperty(a)){d=this.listenerList[a];for(c=0;c<d.length;c++)d[c](a)}},shutdown:function(){this.removeAllListeners()}};return function(){var d=!1,h=!1;return{constants:{UPLOAD_TO_SERVER:"UPLOAD_TO_SERVER",UPLOAD_TO_AVIARY:"UPLOAD_TO_AVIARY",GET_IMAGE_DATA:"GET_IMAGE_DATA",REPLACE_IMAGE:"REPLACE_IMAGE"},
mapToFlashToolName:function(a){switch(a){case "rotate":return"rotate90"}return a},mapFromFlashToolName:function(a){switch(a){case "rotate90":return"rotate"}return a},customBridge:function(a){var d=function(){};d.prototype=new c;d.prototype.constructor=c;for(var e in a)d.prototype[e]=a[e];return d},activate:function(a){this.bridge=a||new c;this.goldenEggCallback=null},setHiresSize:function(a,c){this.canvas&&this.canvas.setHiresSize(a,c)},hiresSizeChanged:function(a,c){AV.paintWidgetInstance&&AV.paintWidgetInstance.actions&&
AV.paintWidgetInstance.actions.setDims(a,c)},startEditing:function(a){this.canvas=null;this.active_target=a;this.bridge.createCanvas()},restartEditing:function(a){this.active_target=a;this._setupEditing()},save:function(){this.bridge.onSave(this.canvas)},close:function(){e.shutdown()},runGoldenEgg:function(a,c,d,e){this.goldenEggCallback=e;this.canvas.renderGoldenEgg(a,c,d)},doCrop:function(){this.canvas.executeCrop()},endEditing:function(){this.bridge.onEndEditing(this.canvas);this.goldenEggCallback=
null},activatePlugin:function(a){this.canvas.activatePlugin(a)},deactivatePlugin:function(a){this.canvas.deactivatePlugin(a)},changeProperty:function(a,c){this.canvas.changeProperty(a,c)},applyPreviewFromPlugin:function(a){this.canvas.applyPreviewFromPlugin(a)},commitChangesFromPlugin:function(a){this.canvas.commitChangesFromPlugin(a)},discardChangesFromPlugin:function(a){this.canvas.discardChangesFromPlugin(a)},resizeCanvas:function(a,c){var d=this.canvas;d.width=a+"px";d.height=c+"px";AV.paintWidgetInstance&&
AV.paintWidgetInstance.setDimensions(a,c)},hideCanvas:function(){this.canvas&&(this.canvas.style.visibility="hidden")},showCanvas:function(){this.canvas&&(this.canvas.style.visibility="visible")},executePlugin:function(){this.canvas.executePlugin()},renderPreview:function(a,c){this.canvas.renderPreview(a,c)},getDynamicPropertyDefaultValue:function(a){return this.canvas.getDynamicPropertyDefaultValue(a)},syncProperty:function(){},syncPreview:function(){},setCanvasDataArray:function(a,c,d){AV.canvasDataReceiver&&
AV.canvasDataReceiver.apply(this,[a,c,d])},onThumbClick:function(a){e.doCallbacks(a)},addThumbClickListener:function(a,c){e.addListener(a,c)},removeAllThumbClickListeners:function(){e.removeAllListeners()},setThumb:function(a,c){var d=document.getElementById("avpw_flashThumb"+a);d&&d.refreshThumb(c)},getHistory:function(){return this.canvas.getHistory()},getFlashGatewayServer:function(){return AV.build.flashGatewayServer},getHiResStickerUrl:function(a){return AV.paintWidgetInstance&&AV.paintWidgetInstance.overlayRegistry?
AV.paintWidgetInstance.overlayRegistry.getHiRes(a):null},getImageData:function(c,d){d&&"function"===typeof d&&(a=d);this.canvas.commit(AV.FlashAPI.constants.GET_IMAGE_DATA,{})},getMaxSize:function(){return AV.launchData.maxEditSize||AV.launchData.maxSize},getMaxBitmapSize:function(){var a=0;"aviary"==AV.launchData.openType&&(a=AV.launchData.maxSize);return a},_cropSelectionStarted:function(){},_onPreviewRendered:function(){},_onPluginLoaded:function(a){AV.paintWidgetInstance.onModuleLoaded(a)},_onImageLoaded:function(a,
c){AV.paintWidgetLauncher_Flash_stage2&&AV.paintWidgetLauncher_Flash_stage2(a,c)},_onGoldenEggComplete:function(){this.goldenEggCallback&&this.goldenEggCallback()},_onCanvasLoaded:function(a){this.canvas=a;this._setupEditing(AV.launchData.url||null)},_onCommitComplete:function(a){this.bridge.onCommitComplete(a)},_onGetImageDataComplete:function(c){a&&(a.apply(this,[c]),a=null)},_setupEditing:function(a){var c=this.bridge.getPlugins(),a=a||this.active_target.src;this.canvas.setup(a,AV.build.proxyServer,
c)},_canUndo:function(){return d},_onUndo:function(){this.canvas.undo()},_canRedo:function(){return h},_onRedo:function(){this.canvas.redo()},_onHistoryChange:function(a,c){d=a;h=c;AV.controlsWidgetInstance&&AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"updateUndoRedo",[a,c])},setCheckpoint:function(a){this.canvas.setCheckpoint(a)},isACheckpoint:function(a){return this.canvas.isACheckpoint(a)},undoToCheckpoint:function(){this.canvas.undoToCheckpoint()},redoToCheckpoint:function(){return this.canvas.redoToCheckpoint()},
truncateActionList:function(){this.canvas.truncateActionList()},_onError:function(a,c){"BAD_IMAGE"===a&&(AV.paintWidgetCloser(!0),AV.launchData.url&&(a="BAD_URL"));AV.errorNotify(a,c)},init:function(a){AV.FlashAPI.activate(function(){if(!a)return new c;if(a.plugins){for(var d=[],e=a.plugins,f=0;f<e.length;++f){var h=AV.FlashAPI.mapToFlashToolName(e[f]),s=AV.toolDefaults[e[f]];s&&s.files&&d.push({id:h,presets:s.presetsFlash,files:s.files})}0<d.length&&(a.getPlugins=function(){return d});delete a.plugins}if(a.action){var p=
a.action;a.onSave=function(a){var c=p.type;p=AV.util.extend(p,{posturl_:AV.launchData.postUrl,hiresUrl_:AV.launchData.hiresUrl,postdata_:AV.launchData.postData,partnerHash_:AV.launchData.apiKey,contenttype_:AV.launchData.fileFormat,jpgQuality_:AV.launchData.jpgQuality,debug_:AV.launchData.debug,asyncSave_:AV.launchData.asyncSave,signature_:AV.launchData.signature,timestamp_:AV.launchData.timestamp,useCustomFileExpiration_:AV.launchData.useCustomFileExpiration});a.commit(c,p)};delete a.action}e=function(){};
e.prototype=new c;e.prototype.constructor=c;for(var u in a)e.prototype[u]=a[u];return new e}())}}}()}();"undefined"==typeof AV&&(AV={});
AV.usageTracker=function(){var a=null,d={},c=0,e=[],f,h=!0,i=!1,k={},j,n,m,s,p,u,z=function(){AV.controlsWidgetInstance&&AV.usageTracker.submit("close")},x=function(){window._gaq=window._gaq||[];if("undefined"===typeof _gat){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)}i||(_gaq.push(["Feather._setAccount",
AV.build.googleTracker]),_gaq.push(["Feather._setCustomVar",1,"apikey",AV.launchData.apiKey]),_gaq.push(["Feather._setCustomVar",2,"featherversion",AV.build.version]),_gaq.push(["Feather._setCustomVar",3,"sessionid",this.getUUID()]),_gaq.push(["Feather._setCustomVar",4,"language",AV.launchData.language]),i=!0)},w=function(){avpw$.each(d,function(a,c){_gaq.push(["Feather._trackEvent","toolusage",a,"count",c])})};k.setup=function(){avpw$(window).bind("unload",z)};k.shutdown=function(){avpw$(window).unbind("unload",
z)};k.clear=function(){a=null;d={};c=0;e=[]};k.getUUID=function(){return a?a:a=Math.floor(4294967295*Math.random()).toString(16)+Math.floor(4294967295*Math.random()).toString(16)};k.addUsage=function(a,e){e||(e=1);d[a]=void 0===d[a]?e:d[a]+e;c+=e};k.setPageCount=function(a){var c;e=Array(a);for(c=0;c<a;c++)e[c]=0};k.addPageHit=function(a){a!==f&&e[a]++;f=a};k.submit=function(a){if("firstclick"===a)if(h)h=!1;else return;x.call(this);"launch"===a?_gaq.push(["Feather._trackPageview"]):_gaq.push(["Feather._trackEvent",
"submit",a,"totalcount",c]);j||(j=avpw$("#avpw_track_form"),n=avpw$("#avpw_track_form_action"),m=avpw$("#avpw_track_form_sessionid"),s=avpw$("#avpw_track_form_apikey"),p=avpw$("#avpw_track_form_data"),u=avpw$("#avpw_img_track_target_holder"));if(AV.build.imgtrackServer&&AV.JSON){n.val(a);m.val(this.getUUID());s.val(AV.launchData.apiKey);switch(a){case "close":a={dataver:1,opentype:AV.launchData.openType,pagehits:e,toolusage:d};p.val(AV.JSON.stringify(a));w();break;case "firstclick":a={toolusage:d};
p.val(AV.JSON.stringify(a));w();break;default:p.val("")}u.html(AV.buildHiddenFrame("avpw_img_track_target"));avpw$("#avpw_img_track_target").load(function(){AV.util.nextFrame(function(){u&&u.length&&u.empty()})});AV.util.nextFrame(function(){j&&(j.length&&u&&u.length&&u.children().length>0)&&j.submit()})}};return k}();
AV.PurchaseManager=function(a){var d={EFFECT:"effect",STICKER:"sticker"},c={},e,f=function(a){var c=a.resourceUrl;c&&(-1===c.indexOf("http")&&(c=AV.build.feather_baseURL+c),a.resourceUrl=c)},h=function(a){for(var c=0;c<e.length;c++)for(var d=0;d<a.length;d++)a[d].assetId===e[c].assetId&&(e[c].purchased=!0,AV.util.extend(e[c],a[d]),f(e[c]))},i=function(a){var c=[];if(a)for(var a=d[a],f=0;f<e.length;f++)e[f].assetType===a&&c.push(e[f]);else c=e.slice(0);return c},k=function(a,d){if(!e)return n.getAssets(a,
function(c){e=c;for(c=0;c<e.length;c++)f(e[c]);n.getPurchasedAssets(a,d)}),!1;try{return window.avpw_purchase_frame.postMessage("getPurchasedAssets","*"),c.getPurchasedAssets=function(c){h(c);d&&d.apply(this,[i(a)])},!0}catch(k){return!1}},j=function(a,c){e=[{needsPurchase:!1,assetId:"original_effects",assetType:"effect",displayName:"Original",resourceUrl:"js/effects_original_effects.js"},{needsPurchase:!1,assetId:"original_stickers",assetType:"sticker",displayName:"Original",resourceUrl:"js/stickers_original_stickers.js"}];
c&&AV.util.nextFrame(function(){for(var d=0;d<e.length;d++)f(e[d]);c.apply(this,[i(a)])});return!0},n=this;n.getAssets=function(a,d){window.setTimeout(function(){try{return window.avpw_purchase_frame.postMessage("getAssets","*"),c.getAssets=d,!0}catch(a){return!1}},2E3)};n.getPurchasedAssets=a?k:j;n.getById=function(a){for(var c=0;c<e.length;c++)if(e[c].assetId===a)return e[c]};n.showAssetPurchaseView=function(a,d){var e={messageName:"showAssetPurchaseView",assetId:a},e=AV.JSON.stringify(e);try{return window.avpw_purchase_frame.postMessage(e,
"*"),c.showAssetPurchaseView=function(){n.showAssetPurchasePopup(a,d)},!0}catch(f){return!1}};n.showAssetPurchasePopup=function(a,d){avpw$("#avpw_purchase_frame").show();AV.controlsWidgetInstance.messager.show("avpw_purchase_pack",!0);avpw$("#avpw_purchase_pack_close").bind("click",n.hideAssetPurchasePopup);c.getPurchasedAssets=function(c){h(c);c=n.getById(a);d&&("function"===typeof d&&c)&&d.apply(this,[c]);n.hideAssetPurchasePopup()}};n.hideAssetPurchasePopup=function(){c.getPurchasedAssets=null;
avpw$("#avpw_purchase_frame").hide();AV.controlsWidgetInstance.messager.hide("avpw_purchase_pack");avpw$("#avpw_purchase_pack_close").unbind("click",n.hideAssetPurchasePopup)};n.messageHandler=function(a){a.messageName&&c[a.messageName]&&c[a.messageName].apply(this,[a.data])};a&&(window.avpw_purchase_frame||avpw$("#avpw_messaging").append(AV.template[AV.launchData.layout].inAppPurchaseFrame({src:AV.build.inAppPurchaseFrameURL})));return n};
AV.getActiveTools=function(a,d){var c=a;"string"===typeof a&&(c=a.split(","));var e=[],f,h={},i;if(d)for(i=0;i<d.length;i++)f=d[i],h[f]=!0;for(i=0;i<c.length;i++)if(f=c[i],!(d&&f in h)&&("stickers"===f&&(f="overlay"),"draw"===f&&(f="drawing"),e.push(f),"aviary"!==AV.launchData.openType&&"mobile"!==AV.launchData.openType&&"overlay"===f&&(f=AV.launchData.stickers,f[0]&&f[0].contents)))for(var k=1;k<f.length;k++)e.push("overlay");return e};
AV.paintWidgetGetPopupEmbedDiv=function(a){var d=avpw$("#avpw_canvas_embed_popup");if(a){var c=avpw$(a),e,f,h="top left bottom right margin-top margin-right margin-bottom margin-left border-top border-right border-bottom border-left padding-top padding-right padding-bottom padding-left".split(" "),i={position:"relative"};for(e=0;e<h.length;e++)f=h[e],i[f]=c.css(f);c=avpw$(a).css("display");if(""==c||"inline"==c)c="inline-block";i.display=c;0==d.length&&(d=document.createElement("div"),d.id="avpw_canvas_embed_popup");
avpw$(d).hide().css(i).insertBefore(a)}return d};AV.paintWidgetLauncher=function(a,d){if(!AV.paintWidgetInstance)return AV.usageTracker.clear(),AV.featherUseFlash?AV.paintWidgetLauncher_Flash(a,d):AV.paintWidgetLauncher_HTML(a,d)};
AV.paintWidgetLauncher_Flash=function(a,d){function c(){avpw$(i).unbind("load",c);AV.msie&&7==AV.msie&&(avpw$("#avpw_controls").css("visibility","hidden"),avpw$("#avpw_controls").show());AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"placeControls_Flash",[AV.launchData.appendTo]);AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"enableControls");j=AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"getScaledImageDims_Flash",[i]);n=j.width;m=j.height;"aviary"==
AV.launchData.openType&&(s=n>m?n:m,AV.launchData.maxEditSize=s);"mobile"!=AV.launchData.openType&&"aviary"!=AV.launchData.openType&&AV.controlsWidgetInstance.setMinWidth(n);AV.paintWidgetInstance=new AV.PaintWidget(n,m);AV.paintWidgetInstance.setOrigSize(n,m);if("aviary"==AV.launchData.openType)var e=AV.template[AV.launchData.layout].flashCanvasBox({id:"canvasContent"});else e=document.createElement("div"),e.id="canvasContent";avpw$(k).append(e);AV.controlsWidgetInstance.initAllTools.call(AV.controlsWidgetInstance);
var h={initsize:j,plugins:p,action:{origUrl_:d?d:f.src,sessionID_:AV.usageTracker.getUUID(),referrerUrl_:window.location.href,type:AV.FlashAPI.constants.UPLOAD_TO_AVIARY,url:AV.build.imgrecvServer,name:"file"}};AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"hideOriginalImage",[f]);"aviary"==AV.launchData.openType&&AV.util.nextFrame(function(){AV.controlsWidgetInstance.setupScrollPanels()});AV.setUpOstrich();AV.msie&&7==AV.msie&&(avpw$("#avpw_controls").hide(),avpw$("#avpw_controls").css("visibility",
"visible"));avpw$("#avpw_controls").fadeIn(300);AV.launchData.noCloseButton&&avpw$("#avpw_control_cancel_pane").css("display","none");setTimeout(function(){AV.FlashAPI.init(h);AV.FlashAPI.startEditing(a);AV.controlsWidgetInstance.initWithPaintWidget(AV.paintWidgetInstance);AV.controlsWidgetInstance.setPanelMode(null);AV.controlsWidgetInstance.loaderPhase=1},300)}function e(){AV.util.imgOnLoad(i,c);avpw$(i).attr("src",h)}var f=AV.util.getImageElem(a),h=f.src,i,k,j,n,m,s,p=AV.getActiveTools(AV.launchData.tools,
["whiten","barrel","bulge","pinch","warmth"]);AV.controlsWidgetInstance=new AV.ControlsWidget(null,a,p);avpw$(".avpw_isa_previewcanvas").hide();k=AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"getEmbedElement",[f]);avpw$(k).show();window.addEventListener&&window.addEventListener("message",AV.controlsWidget_MessageHandler,!1);i=document.createElement("img");avpw$(i).css({display:"block",visibility:"hidden",position:"absolute"}).attr("src",d?d:f.src);AV.build.bundled?e():AV.util.loadFile(AV.build.feather_baseURL+
"js/featherpaint_flash.js","js",e)};
AV.paintWidgetLauncher_Flash_stage2=function(a,d){var c,e;AV.controlsWidgetInstance.loaderPhase=2;c=AV.launchData.hiresWidth;e=AV.launchData.hiresHeight;c&&e?(c=c?parseInt(c):0,e=e?parseInt(e):0,AV.paintWidgetInstance.actions.setOrigSize(c,e)):AV.launchData.hiresUrl&&AV.paintWidgetInstance.actions.setOrigSize(a,d);AV.controlsWidgetInstance.setImageScaledIndicator();AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"launchStage2_Flash");AV.controlsWidgetInstance.showWaitThrobber(!1);avpw$(AV.controlsWidgetInstance.onEggWaitThrobber).hide();
AV.controlsWidgetInstance.showFlashThumbs(null,!1);AV.usageTracker.submit("launch");AV.fireLaunchComplete()};
AV.paintWidgetLauncher_HTML=function(a,d){var c=AV.util.getImageElem(a),e,f,h,i;i="mobile"==AV.launchData.openType?AV.getActiveTools(AV.launchData.tools,["resize"]):AV.getActiveTools(AV.launchData.tools);AV.isRelaunched&&"undefined"!=typeof c.avpw_prevURL&&(d=c.avpw_prevURL);AV.controlsWidgetInstance=new AV.ControlsWidget(null,a,i);AV.controlsWidgetInstance.origURL=d?d:avpw$(c).attr("src");AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"placeControls",[AV.launchData.appendTo]);AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,
"enableControls");"mobile"!=AV.launchData.openType&&"aviary"!=AV.launchData.openType&&AV.setUpOstrich();avpw$("#avpw_controls").fadeIn(300);("mobile"==AV.launchData.openType||"aviary"==AV.launchData.openType)&&AV.util.nextFrame(function(){"mobile"==AV.launchData.openType&&AV.setPageWidth(avpw$("#avpw_controls").width());AV.controlsWidgetInstance.setupScrollPanels()});AV.launchData.noCloseButton&&avpw$("#avpw_control_cancel_pane").css("display","none");if(c&&"canvas"===c.nodeName.toLowerCase())AV.mockLauncher(c);
else return window.addEventListener("message",AV.controlsWidget_MessageHandler,!1),f=AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"getEmbedElement",[c]),e=document.createElement("img"),e.id="avpw_temp_loading_image",AV.tempLoadingImageSrc=e.src,avpw$(e).load(function(){h=AV.controlsWidgetInstance.getScaledDims(avpw$(c).width(),avpw$(c).height());e.width=h.width;e.height=h.height;AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"getScaledImageDims",[e]);avpw$(e).unbind();
e.style.display="block";avpw$(f).append(e);AV.controlsWidgetInstance.showWaitThrobber(!0);AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"hideOriginalImage",[c]);avpw$(f).show();AV.util.nextFrame(function(){AV.build.bundled?AV.paintWidgetLauncher_stage2(a,d):AV.util.loadFile(AV.build.feather_baseURL+"js/featherpaint.js","js",function(){AV.paintWidgetLauncher_stage2(a,d)})})}).error(function(){AV.paintWidgetCloser(!0);AV.errorNotify("BAD_IMAGE",[d])}),e.src=c.src,!1};
AV.mockLauncher=function(a){var d=AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"getEmbedElement",[a]);AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"getScaledImageDims",[a]);avpw$(a).detach();avpw$(d).append(a);avpw$(d).show();AV.controlsWidgetInstance.showWaitThrobber(!0);AV.util.nextFrame(function(){var a=function(){};AV.controlsWidgetInstance.initAllTools=function(){for(var a in this.activeTools){var c=this.activeTools[a];this.tool.hasOwnProperty(c)&&this.moduleNotify(c,
"init",[this])}};AV.controlsWidgetInstance.initWithPaintWidget=function(a){this.paintWidget=a;this.initAllTools();this.bindControls();this.paintWidget.showWaitThrobber=this.showWaitThrobber.AV_bindInst(this)};AV.controlsWidgetInstance.loaderPhase=1;AV.paintWidgetInstance={moduleLoaded:function(a,c){return c.call(this)},setMode:a,setCurrentLayerByName:a,shutdown:a,actions:{setCheckpoint:a}};AV.controlsWidgetInstance.initWithPaintWidget(AV.paintWidgetInstance);AV.controlsWidgetInstance.showWaitThrobber(!1);
AV.controlsWidgetInstance.loaderPhase=2;AV.fireLaunchComplete()})};
AV.paintWidgetLauncher_stage2=function(a,d){var c=AV.util.getImageElem(a),e,f,h,i,k=function(a){AV.controlsWidgetInstance&&AV.paintWidgetInstance&&(e=new Image,avpw$(e).load(function(){AV.controlsWidgetInstance&&AV.paintWidgetInstance&&(h&&i?(h=h?parseInt(h):0,i=i?parseInt(i):0,AV.paintWidgetInstance.actions.setOrigSize(h,i)):AV.launchData.hiresUrl&&AV.paintWidgetInstance.actions.setOrigSize(e.width,e.height),f=AV.controlsWidgetInstance.getScaledDims(e.width,e.height),e.width=f.width,e.height=f.height,
AV.paintWidgetInstance.setDimensions(f.width,f.height),AV.paintWidgetInstance.setBackground(e),AV.paintWidgetInstance.setOrigSize(f.width,f.height),AV.controlsWidgetInstance.setImageScaledIndicator(),c.src!==d&&AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"scaleCanvas"),avpw$(AV.paintWidgetInstance.canvas).insertBefore("#avpw_temp_loading_image"),j.remove(),AV.tempLoadingImageSrc=d,AV.controlsWidgetInstance.showWaitThrobber(!1),AV.controlsWidgetInstance.loaderPhase=2)}).attr("src",
a))};f=AV.controlsWidgetInstance.getScaledDims(avpw$(c).width(),avpw$(c).height());AV.controlsWidgetInstance.loaderPhase=1;"mobile"!=AV.launchData.openType&&"aviary"!=AV.launchData.openType&&AV.controlsWidgetInstance.setMinWidth(f.width);AV.paintWidgetInstance=new AV.PaintWidget(f.width,f.height);AV.controlsWidgetInstance.canvasUI=new AV.PaintUI(AV.paintWidgetInstance.canvas);AV.paintWidgetInstance.setOrigSize(f.width,f.height);h=AV.launchData.hiresWidth;i=AV.launchData.hiresHeight;h&&i?(h=h?parseInt(h):
0,i=i?parseInt(i):0,AV.paintWidgetInstance.actions.setOrigSize(h,i)):AV.launchData.hiresUrl&&AV.paintWidgetInstance.actions.setOrigSize(c.width,c.height);AV.controlsWidgetInstance.setImageScaledIndicator();AV.controlsWidgetInstance.initWithPaintWidget(AV.paintWidgetInstance);var j=avpw$("#avpw_temp_loading_image");AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"scaleCanvas");null!=d?-1===d.indexOf("data:")?avpw$.ajax({type:"GET",dataType:"json",url:AV.build.jsonp_imgserver+"?callback=?",
data:{url:escape(d)},success:function(a){k(a.data)},error:function(a,c){if(a.status===200&&c==="parsererror"&&AV.controlsWidgetInstance){AV.controlsWidgetInstance.showWaitThrobber(false);AV.util.nextFrame(function(){AV.paintWidgetCloser(true);AV.errorNotify("BAD_URL",[d])})}}}):k(d):(AV.paintWidgetInstance.setBackground(c),avpw$("#avpw_controls").insertAfter(AV.paintWidgetInstance.canvas),avpw$(AV.paintWidgetInstance.canvas).insertBefore(j),j.remove(),AV.tempLoadingImageSrc=c.src,AV.controlsWidgetInstance.showWaitThrobber(!1),
AV.controlsWidgetInstance.loaderPhase=2);AV.usageTracker.submit("launch");AV.fireLaunchComplete();return!1};AV.fireLaunchComplete=function(){AV.launchData.initTool&&AV.controlsWidgetInstance.setActiveTool(AV.launchData.initTool);if("function"===typeof AV.launchData.onReady)AV.launchData.onReady()};
AV.paintWidgetShutdown=function(){window.removeEventListener&&window.removeEventListener("message",AV.controlsWidget_MessageHandler,!1);avpw$("#avpw_controls").hide();AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"onShutdown");if("function"===typeof AV.launchData.onClose)AV.launchData.onClose(AV.paintWidgetInstance.dirty);AV.paintWidgetInstance.shutdown();AV.controlsWidgetInstance.shutdown();AV.featherUseFlash&&AV.FlashAPI.close();AV.usageTracker.submit("close");AV.paintWidgetInstance=
null;AV.controlsWidgetInstance=null;AV.tempLoadingImageSrc=null};AV.paintWidgetCloser=function(a){AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"onClose",[a]);a?(avpw$("#avpw_controls").hide(),AV.paintWidgetShutdown()):avpw$("#avpw_controls").fadeOut(300,function(){AV.paintWidgetInstance&&AV.paintWidgetShutdown()})};
AV.controlsWidget_onImageSaved=function(a,d){var c;"function"===typeof AV.launchData.onSave&&(c=AV.launchData.onSave.apply(AV.launchData,[AV.util.getImageId(AV.controlsWidgetInstance.paintImgIdElem),a,d]));AV.controlsWidgetInstance&&(AV.util.getImageElem(AV.controlsWidgetInstance.paintImgIdElem).avpw_prevURL=a,AV.controlsWidgetInstance.showView("main"),AV.controlsWidgetInstance.setPanelMode(null),!1!==c&&("mobile"==AV.launchData.openType||"aviary"==AV.launchData.openType?AV.controlsWidgetInstance.messager.show("avpw_aviary_beensaved",
!0):(AV.controlsWidgetInstance.setLastToolsPage("avpw_aviary_beensaved"),setTimeout(function(){AV.controlsWidgetInstance.didJumpToLastPage=!0;AV.controlsWidgetInstance.goToToolsPage(AV.controlsWidgetInstance.toolsPager.getLastPage())},5))),AV.controlsWidgetInstance.paintWidget.dirty=!1,AV.controlsWidgetInstance.saving=!1)};
AV.controlsWidget_MessageHandler=function(a){var d=a.data,c;if(""!=AV.build.feather_baseURL&&(c=AV.util.getDomain(a.origin),"aviary.com"!=c&&("aviary.local"!=c&&"viary.com"!=c&&"amazonaws.com"!=c)&&(a=AV.util.getDomain(AV.build.feather_baseURL),""==a||""==c||a!=c)))return;if(d.substr&&"avpw:"==d.substr(0,5))a=d.substr(5).split("---FEATHER-POSTMESSAGE---"),d=a[0],a=a[1],avpw$("#avpw_img_submit_target").unbind("load"),avpw$("#avpw_img_submit_target_holder").empty(),AV.controlsWidget_onImageSaved(d,
a);else try{(d=AV.JSON.parse(d))&&d.messageName&&AV.controlsWidgetInstance.purchaseManager.messageHandler(d)}catch(e){}};
AV.ControlsWidget=function(a,d,c){this.maxHeight=this.maxWidth=parseInt(AV.launchData.maxSize);this.saving=!1;this.origURL=null;this.activeTools=c;this.didJumpToLastPage=!1;this.quitCount=0;AV.usageTracker.setup();this.paintImgIdElem=d;this.curMode=null;if("aviary"==AV.launchData.openType||"mobile"==AV.launchData.openType)this.purchaseManager=new AV.PurchaseManager(AV.launchData.allowInAppPurchase);"mobile"!=AV.launchData.openType&&"aviary"!=AV.launchData.openType&&(this.filterEggs&&this.filterEggs.setup.call(this),
this.populatePulldown("crop"),this.populatePulldown("resize"),AV.formFields&&(AV.formFields.checkbox_style_startup(),AV.formFields.dropdown_style_startup()),this.setupScrollPanels(),this.setLastToolsPage("avpw_aviary_about"));this.layoutNotify(AV.launchData.openType,"subscribeToResize",["setupScrollPanels",this.setupScrollPanels.AV_bindInst(this)]);this.showView("main",1);a&&this.initWithPaintWidget(a);a={id:"avpw_tool_spinner",lines:12,length:6,width:2,radius:6,color:"#fff",speed:0.5,trail:70};"mobile"!=
AV.launchData.openType&&(a.color="#555",a.length=4);this.waitThrobber=new AV.Spinner({id:"avpw_canvas_spinner",lines:12,length:6,width:2,radius:6,color:"#fff",speed:0.5,trail:70});this.onEggWaitThrobber=new AV.Spinner(a)};AV.ControlsWidget.prototype.tool={};AV.ControlsWidget.prototype.layout={};AV.ControlsWidget.prototype.moduleNotify=function(a,d,c){return this.objectNotify("tool",a,d,c)};AV.ControlsWidget.prototype.layoutNotify=function(a,d,c){return this.objectNotify("layout",a,d,c)};
AV.ControlsWidget.prototype.objectNotify=function(a,d,c,e){return"object"==typeof this[a][d]&&(a=this[a][d],"function"==typeof a[c])?(c=a[c],e||(e=[]),c.apply(a,e)):!0};
AV.ControlsWidget.prototype.shutdown=function(){"mobile"!=AV.launchData.openType&&"aviary"!=AV.launchData.openType&&AV.formFields&&(AV.formFields.checkbox_style_shutdown(),AV.formFields.dropdown_style_shutdown());this.canvasUI&&this.canvasUI.shutdown();this.messager&&this.messager.hide();this.layoutNotify(AV.launchData.openType,"unsubscribeToResize",["setupScrollPanels"]);this.shutdownAllTools();this.unbindControls();this.toolsPager&&(this.toolsPager.shutdown(),this.toolsPager=null);this.paintWidget.showWaitThrobber=
null;AV.usageTracker.shutdown();this.waitThrobber.stop();this.onEggWaitThrobber.stop();this.onEggWaitThrobber=this.waitThrobber=null;this.showPanel(null)};AV.ControlsWidget.prototype.initAllTools=function(){AV.paintWidgetInstance.filterManager.loadPack("tools");for(var a in this.activeTools){var d=this.activeTools[a];this.tool.hasOwnProperty(d)&&AV.paintWidgetInstance.moduleLoaded(d,function(a){this.moduleNotify(a,"init",[this])}.AV_bindInst(this))}};
AV.ControlsWidget.prototype.shutdownAllTools=function(){for(var a in this.activeTools)this.moduleNotify(this.activeTools[a],"shutdown")};AV.ControlsWidget.prototype.bindControls=function(){};AV.ControlsWidget.prototype.unbindControls=function(){};AV.ControlsWidget.prototype.initWithPaintWidget=function(a){this.paintWidget=a;AV.featherUseFlash||this.initAllTools();this.bindControls();this.paintWidget.showWaitThrobber=this.showWaitThrobber.AV_bindInst(this)};
AV.ControlsWidget.prototype.setActiveTool=function(a,d){var c=function(){if(!this.paintWidget.busy){this.setPanelModeFromMain(a,d);AV.controlsWidgetInstance.onEggWaitThrobber.stop();if("mobile"==AV.launchData.openType){var c=d.getAttribute("data-header");c&&(document.getElementById("avpw_control_toolname").innerHTML=c)}AV.usageTracker.addUsage(a)}}.AV_bindInst(this);if(-1<a.indexOf("overlay")){if("aviary"!==AV.launchData.openType&&"mobile"!==AV.launchData.openType){var e=a.split("overlay_")[1];e&&
this.tool.overlay.setStickerGroupIndex(e)}a="overlay"}-1<a.indexOf("effects")&&((e=a.split("effects_")[1])&&this.tool.effects.setFilterPack(e),a="effects");!this.paintWidget.moduleLoaded(a,c)&&d&&(this.onEggWaitThrobber.stop(),this.onEggWaitThrobber.spin(avpw$(d).children(".avpw_icon_waiter")[0]))};AV.ControlsWidget.prototype.setMinWidth=function(a){AV.msie&&!(8<=AV.msie)&&(a=parseInt(a)+330,avpw$("#avpw_wrapper_1").css("min-width",a))};
AV.ControlsWidget.prototype.showWaitThrobber=function(a,d){if(a){var c=this.layoutNotify(AV.launchData.openType,"getEmbedElement");c.is(":visible")&&(this.waitThrobber.spin(c[0]),avpw$(this.waitThrobber).fadeIn(300))}else avpw$(this.waitThrobber.el).fadeOut(300,this.waitThrobber.stop);d&&window.setTimeout(d,5)};AV.ControlsWidget.prototype.panelMode2WidgetMode=function(a){switch(a){case "rotate":return"rotate90";case "greeneye":return"redeye";case "pinch":return"bulge"}return a};
AV.ControlsWidget.prototype.setPanelMode=function(a){if(this.canvasUI)this.canvasUI.onModeChange(a);this.moduleNotify(this.curMode,"panelWillClose");this.moduleNotify(a,"panelWillOpen");this.resizeFlashThumbs(a);this.paintWidget.setMode(this.panelMode2WidgetMode(a));this.showPanel(a);this._resetUI(a);this.paintWidget.setCurrentLayerByName("background");var d=this;window.setTimeout(function(){d.moduleNotify(this.curMode,"panelDidClose");d.moduleNotify(a,"panelDidOpen")},200);this.curMode=a;this.layoutNotify(AV.launchData.openType,
"disableZoomMode")};AV.ControlsWidget.prototype.setPanelModeFromMain=function(a){this.showView("editpanel");this.setPanelMode(a)};AV.ControlsWidget.prototype.showView=function(){};
AV.ControlsWidget.prototype.setupScrollPanels=function(){var a,d,c=this,e=0,f,h={},i;"mobile"==AV.launchData.openType?(f=null,i=AV.PAGE_WIDTH):"aviary"==AV.launchData.openType?(i=this.layoutNotify(AV.launchData.openType,"getDims").TOOLS_BROWSER_WIDTH,f=AV.template[AV.launchData.layout].aviaryScrollPanel,h={panelWidth:i,panelClass:"avpw_scroll_page_complete"}):(f=AV.template[AV.launchData.layout].aviaryScrollPanel,i=248,avpw$("#avpw_control_main_scrolling_region").width(99999));f={itemCount:this.activeTools.length,
itemsPerPage:this.layoutNotify(AV.launchData.openType,"getToolsPerPage"),pageWidth:i,leftArrow:avpw$("#avpw_lftArrow"),rightArrow:avpw$("#avpw_rghtArrow"),itemBuilder:function(f){a=c.activeTools[f];if(a=="overlay")if(AV.launchData.openType!=="aviary"&&AV.launchData.openType!=="mobile"){f=AV.launchData.stickers;if(f[e]&&f[e].label){d=f[e].label;a="overlay_"+e;e++}else d=AV.getLocalizedString("Stickers")}else d=AV.getLocalizedString("Stickers");else d=a=="barrel"?AV.getLocalizedString("Bulge"):a=="drawing"?
AV.getLocalizedString("Draw"):a.substr(0,1).toUpperCase()+a.substr(1);d=AV.getLocalizedString(d);return AV.template[AV.launchData.layout].eggIcon({optionName:a,capOptionName:d})},pageTemplate:AV.template[AV.launchData.layout].genericScrollPanel,pipTemplate:AV.template[AV.launchData.layout].scrollPanelPip,lastPageTemplate:f,lastPageContents:h,pageContainer:avpw$("#avpw_control_main_scrolling_region"),pipContainer:avpw$("#avpw_tools_pager ul"),onPageLeft:function(){c.didJumpToLastPage?c.goToPreviousToolsPage.call(c):
c.toolsPager.pageLeft.call(this);return false},onPageChange:function(a){AV.usageTracker.addPageHit(a)}};this.toolsPager=new AV.Pager(f);AV.usageTracker.setPageCount(this.toolsPager.getPageCount());"aviary"==AV.launchData.openType&&avpw$("#avpw_control_main_scrolling_region").css("width",this.toolsPager.getPageCount()*i+"px");this.toolsPager.changePage()};AV.ControlsWidget.prototype.setLastToolsPage=function(a){avpw$(".avpw_isa_last_panel").hide();avpw$("#"+a).show()};
AV.ControlsWidget.prototype.goToToolsPage=function(a,d,c){this.toolsPager.setCurrentPage(parseInt(a));this.toolsPager.changePage(d,c)};AV.ControlsWidget.prototype.goToPreviousToolsPage=function(){var a=this;this.didJumpToLastPage=!1;this.goToToolsPage(this.toolsPager.getPreviousPage(),!1,function(){a.setLastToolsPage("avpw_aviary_about")})};
AV.ControlsWidget.prototype.messager=function(){var a={},d,c,e;return{show:function(e,h,i){d=d||avpw$("#avpw_messaging");c=c||avpw$("#avpw_messaging_inner");e=a[e]||(a[e]=avpw$("#"+e));c.append(e);d.show();h?(d.data("needsConfirmation",!0),AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"disableControls")):(d.data("needsConfirmation",!1),i||window.setTimeout(this.hide,1E3))},hide:function(c,h){d=d||avpw$("#avpw_messaging");e=e||avpw$("#avpw_messages");if(c){var i=a[c];i&&e.append(i)}else avpw$.each(a,
function(a,c){e.append(c)});d.data("needsConfirmation")?(window.setTimeout(function(){h&&h()},400),AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"enableControls")):(d.hide(),h&&h())},addMessage:function(a){e=e||avpw$("#avpw_messages");a&&(e[0].innerHTML+=a)}}}();AV.ControlsWidget.prototype.orientationChanged=function(){};
AV.ControlsWidget.prototype.windowResized=function(){var a=null;return function(){window.clearTimeout(a);a=window.setTimeout(function(){AV.controlsWidgetInstance.canvasUI&&AV.controlsWidgetInstance.canvasUI.resetOffset();AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"onResize");a=null},500)}}();
AV.ControlsWidget.prototype.Slider=function(a){var d=!1,c=function(c,e){!d&&a.onstart&&a.onstart.apply(this,[c,e])},e=function(c,e){!d&&a.onchange&&a.onchange.apply(this,[c,e])},f=function(c,e){!d&&a.onslide&&a.onslide.apply(this,[c,e])},h=avpw$(a.element).slider({range:"min",max:a.max,min:a.min,value:a.defaultValue||a.max/2,delay:a.delay});this.getValue=function(){return h.slider("value")};this.setValue=function(a){return h.slider("value",a)};this.reset=function(){d=!0;this.setValue(a.defaultValue);
d=!1};this.addListeners=function(){h.bind("slidestart",c).bind("slidechange",e).bind("slide",f)};this.removeListeners=function(){h.unbind("slidestart").unbind("slide").unbind("slidechange")};this.shutdown=function(){h.slider("destroy")};return this};
AV.ControlsWidget.prototype.Thumbs=function(a){var d=a.elements,c=function(a,c){var h=this;return function(){a&&a.apply(h,[d[c],c])}};this.addListeners=function(){for(var e=0;e<d.length;e++)AV.featherUseFlash?AV.FlashAPI.addThumbClickListener("avpw_flashThumb"+(e+1),c(a.onclick,e)):avpw$(d[e]).bind("click",c(a.onclick,e))};this.removeListeners=function(){AV.featherUseFlash?AV.FlashAPI.removeAllThumbClickListeners():avpw$(d).unbind("click")};this.reset=function(){for(var c=0;c<d.length;c++)a.onreset&&
a.onreset.apply(this,[d[c],c])};return this};AV.ControlsWidget.prototype.setImageScaledIndicator=function(){AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"updateImageScaledIndicator",[AV.featherUseFlash&&"mobile"!==AV.launchData.openType&&"aviary"!==AV.launchData.openType||AV.launchData.hiresUrl||AV.launchData.hiresWidth||AV.launchData.hiresHeight])};
AV.ControlsWidget.prototype._drawUICircle=function(a,d,c,e){AV.featherUseFlash?this._drawUICircle_Flash(a,d,c,e):this._drawUICircle_HTML(a,d,c,e)};AV.ControlsWidget.prototype._drawUICircle_Flash=function(a,d,c,e){d=parseInt(d);c=AV.util.color_to_int(c);"transparent"==e?(a=!0,e=0):(a=!1,e=e?parseInt(e.slice(1),16):16777215);AV.getFlashMovie("avpw_flashThumb1").setBrushThumb(d,c,e,a)};
AV.ControlsWidget.prototype._drawUICircle_HTML=function(a,d,c,e){var a=avpw$(a)[0],f=a.getContext("2d");f.clearRect(0,0,a.width,a.height);"transparent"!==e&&this._drawUIGrid(f,a.width,a.height);f.globalCompositeOperation="source-over";null!=c?(f.strokeStyle="transparent"==c||AV.util.color_is_white(c)||null==e?"#444":c,c=3):(f.strokeStyle="rgba(0,0,0,0)",c=1);f.lineWidth=c;f.beginPath();f.arc(a.width/2,a.height/2,d,0,2*Math.PI,!0);f.stroke();f.closePath();null!=e&&(f.save(),f.clip(),"transparent"==
e?this._drawUIGrid(f,a.width,a.height):(f.fillStyle=e,f.fillRect(0,0,a.width,a.height)),f.restore())};AV.ControlsWidget.prototype._drawUIGrid=function(a,d,c,e){var f;e||(e=5);for(f=0;f<c+e;f+=e)for(d=0;d<c+e;d+=e)a.fillStyle=1==(d+f&1)?"#fff":"#ddd",a.fillRect(d,f,e,e)};AV.ControlsWidget.prototype.showPanel=function(a){null!=a&&(avpw$(".avpw_controlpanel").each(function(){avpw$(this).hide()}),avpw$("#avpw_controlpanel_"+a).show())};
AV.ControlsWidget.prototype.showFlashThumbs=function(a,d){if(AV.featherUseFlash){var c,e,f,h;c=a?avpw$("#avpw_controlpanel_"+a+" .avpw_flashthumb_holder"):avpw$(".avpw_flashthumb_holder");d?avpw$(c).each(function(a,c){e="avpw_flashThumb"+(a+1);h=AV.getFlashMovie(e);h.width=avpw$(c).width();h.height=avpw$(c).height();f=avpw$(c).offset();f.top+=1;f.left+=1;avpw$("#"+e).offset(f)}):avpw$(c).each(function(a){e="avpw_flashThumb"+(a+1);avpw$("#"+e).offset({top:-9999,left:-9999})})}};
AV.ControlsWidget.prototype.resizeFlashThumbs=function(a){if(AV.featherUseFlash){var d,c,a=avpw$("#avpw_controlpanel_"+a+" .avpw_flashthumb_holder");avpw$(a).each(function(a,f){d="avpw_flashThumb"+(a+1);c=AV.getFlashMovie(d);var h=avpw$(f).prop("width"),i=avpw$(f).prop("height");h||(h=avpw$(f).width());i||(i=avpw$(f).height());h&&i&&(c.width=h,c.height=i)})}};
AV.ControlsWidget.prototype.save=function(){var a=function(){var a=this.paintWidget.exportImage().base64data,c=function(){AV.simpleXHRPost(AV.build.imgrecvServer,{postdata:AV.launchData.postData,posturl:AV.launchData.postUrl,apikey:AV.launchData.apiKey,sessionid:AV.usageTracker.getUUID(),actionlist:this.paintWidget.actions.exportJSON(!0),origurl:this.origURL,encodedas:"base64text",hiresurl:AV.launchData.hiresUrl,contenttype:AV.launchData.fileFormat,jpgquality:AV.launchData.jpgQuality,debug:AV.launchData.debug,
asyncsave:AV.launchData.asyncSave,signature:AV.launchData.signature,timestamp:AV.launchData.timestamp,usecustomfileexpiration:AV.launchData.useCustomFileExpiration,file:a},this.saveCallback_XHR.AV_bindInst(this))||e.call(this)},e=function(){var c="avpw_img_submit_target_"+Math.floor(4294967295*Math.random()).toString(16);avpw$("#avpw_img_submit_target_holder").html(AV.buildHiddenFrame("avpw_img_submit_target",c));avpw$("#avpw_save_form").attr("target",c);avpw$("#avpw_img_submit_target").load(function(){this.saveCallback_form(c)}.AV_bindInst(this));
avpw$("#avpw_save_form_data").val(a);avpw$("#avpw_save_form_postdata").val(AV.launchData.postData);avpw$("#avpw_save_form_posturl").val(AV.launchData.postUrl);avpw$("#avpw_save_form_apikey").val(AV.launchData.apiKey);avpw$("#avpw_save_form_sessionid").val(AV.usageTracker.getUUID());avpw$("#avpw_save_form_actionlist").val(this.paintWidget.actions.exportJSON(!0));avpw$("#avpw_save_form_origurl").val(this.origURL);avpw$("#avpw_save_form_hiresurl").val(AV.launchData.hiresUrl);avpw$("#avpw_save_form_contenttype").val(AV.launchData.fileFormat);
avpw$("#avpw_save_form_jpgquality").val(AV.launchData.jpgQuality);avpw$("#avpw_save_form_debug").val(AV.launchData.debug);avpw$("#avpw_save_form_asyncsave").val(AV.launchData.asyncSave);avpw$("#avpw_save_form_signature").val(AV.launchData.signature);avpw$("#avpw_save_form_timestamp").val(AV.launchData.timestamp);avpw$("#avpw_save_form_usecustomfileexpiration").val(AV.launchData.useCustomFileExpiration);avpw$("#avpw_save_form").submit()},f=this;this.paintWidget.showWaitThrobber(!0,function(){avpw$.support.cors&&
(!AV.firefox||AV.firefox>=4)?c.call(f):e.call(f)});return!1};return function(){if(2>AV.controlsWidgetInstance.loaderPhase||this.saving)return!1;this.moduleNotify(this.curMode,"commit");this.showView("main");this.setPanelMode(null);this.saving=!0;AV.prevActionList=this.paintWidget.actions.exportJSON(!0);AV.launchData.postData&&"string"!==typeof AV.launchData.postData&&(AV.launchData.postData=AV.JSON.stringify(AV.launchData.postData));return AV.featherUseFlash?(AV.FlashAPI.save(),!1):a.call(this)}}();
AV.ControlsWidget.prototype.onSaveButtonClicked=function(){return"function"===typeof AV.launchData.onSaveButtonClicked&&!1===AV.launchData.onSaveButtonClicked.apply(AV.launchData,[AV.util.getImageId(AV.controlsWidgetInstance.paintImgIdElem)])?!1:AV.controlsWidgetInstance.save()};AV.ControlsWidget.prototype.saveCallback_form=function(a){this.paintWidget&&(this.paintWidget.showWaitThrobber(!1),window.avpw_img_submit_target_announcer.postMessage("avpw_load:"+a,"*"))};
AV.ControlsWidget.prototype.saveCallback_XHR=function(a){this.paintWidget.showWaitThrobber(!1);var d=avpw$(a).find("error");if(0<d.length)alert("file submission error: "+d.text());else{var c,e;if(d=avpw$(a).find("url"))c=d.text(),c=c.replace(/^\s+|\s+$/g,""),avpw$(AV.util.getImageElem(this.paintImgIdElem)).avpw_prevURL=c;if(a=avpw$(a).find("hiresurl"))e=a.text(),e=e.replace(/^\s+|\s+$/g,"");AV.controlsWidget_onImageSaved(c,e)}};
AV.ControlsWidget.prototype.showAreYouSure=function(){"mobile"==AV.launchData.openType||"aviary"==AV.launchData.openType?this.messager.show("avpw_aviary_quitareyousure",!0):(this.showView("main"),this.setPanelMode(null),this.setLastToolsPage("avpw_aviary_quitareyousure"),AV.util.nextFrame(function(){this.didJumpToLastPage=!0;this.goToToolsPage(this.toolsPager.getLastPage())}.AV_bindInst(this)))};
AV.ControlsWidget.prototype.cancel=function(){this.quitCount++;var a=0<this.quitCount&&this.paintWidget.dirty;if("function"===typeof AV.launchData.onCloseButtonClicked&&!1===AV.launchData.onCloseButtonClicked.apply(AV.launchData,[a]))return!1;a?this.showAreYouSure():AV.paintWidgetCloser();return!1};
AV.ControlsWidget.prototype.undo=function(){if(this.paintWidget.busy||!1===this.moduleNotify(this.curMode,"onUndo"))return!1;this.paintWidget.undo();"mobile"!=AV.launchData.openType&&"aviary"!=AV.launchData.openType&&this.setMinWidth(this.paintWidget.width);this.moduleNotify(this.curMode,"onUndoComplete");return!1};
AV.ControlsWidget.prototype.undoToCheckpoint=function(){if(this.paintWidget.busy||!1===this.moduleNotify(this.curMode,"onUndo",[{global:!0}]))return!1;this.paintWidget.actions.undoToCheckpoint();this.moduleNotify(this.curMode,"onUndoComplete",[{global:!0}]);return!1};
AV.ControlsWidget.prototype.redo=function(){if(this.paintWidget.busy||!1===this.moduleNotify(this.curMode,"onRedo"))return!1;this.paintWidget.redo();"mobile"!=AV.launchData.openType&&"aviary"!=AV.launchData.openType&&this.setMinWidth(this.paintWidget.width);this.moduleNotify(this.curMode,"onRedoComplete");return!1};
AV.ControlsWidget.prototype.redoToCheckpoint=function(){if(this.paintWidget.busy||!1===this.moduleNotify(this.curMode,"onRedo",[{global:!0}]))return!1;var a=this.paintWidget.actions.redoToCheckpoint();a&&this.moduleNotify(this.curMode,"onRedoComplete",[{global:!0}]);return a};AV.ControlsWidget.prototype._resetUI=function(a){this.moduleNotify(a,"resetUI")};AV.ControlsWidget.prototype.getScaledDims=function(a,d){return AV.util.getScaledDims(a,d,this.maxWidth,this.maxHeight)};
AV.Pager=function(a){var d,c=0,e=0,f=parseInt((a.itemCount-1)/a.itemsPerPage)+1,h=0,i=function(){for(var c="",d=0;d<f;d++)c+=a.pipTemplate({i:d});return c},k=function(){d.removeClass("avpw_page_selected");d.filter('[pagenum="'+c+'"]').addClass("avpw_page_selected")},j=function(){0==c?avpw$(a.leftArrow).removeClass("avpw_prev_enabled").addClass("avpw_prev_disabled"):avpw$(a.leftArrow).removeClass("avpw_prev_disabled").addClass("avpw_prev_enabled");c==f-1?avpw$(a.rightArrow).removeClass("avpw_next_enabled").addClass("avpw_next_disabled"):
avpw$(a.rightArrow).removeClass("avpw_next_disabled").addClass("avpw_next_enabled")},n=function(a,c){var d=avpw$(".avpw_arrow"),e=function(){d.addClass("avpw_arrow_visible")};d.removeClass("avpw_arrow_visible");window.setTimeout(function(){a.apply(this,c);window.setTimeout(e,600)},200)},m=function(e,i){var m=a.pageContainer,q;if(0>c){if(c=0,"mobile"==AV.launchData.openType||"aviary"==AV.launchData.openType)return}else if(c>f-1&&(c=f-1,"mobile"==AV.launchData.openType||"aviary"==AV.launchData.openType))return;
(q=c*a.pageWidth)&&(q-=h);if("mobile"==AV.launchData.openType){var p=AV.support.getVendorProperty("transform");n(function(){m[0].style[p]=0<c?"translateX(-"+q+"px)":"translateX(0)";j()})}else{if("aviary"==AV.launchData.openType)(p=AV.support.getVendorProperty("transform"))?m[0].style[p]=0<c?"translateX(-"+q+"px)":"translateX(0)":m[0].style.left=0<c?"-"+q+"px":"0";else{var s=avpw$(m).parent();e?s.animate({scrollLeft:q},1,"swing",i):s.animate({scrollLeft:q},300,"swing",i)}j()}a.onPageChange&&a.onPageChange.apply(this,
[c]);d&&k()},s=function(){e=c;c+=-1;m.call(this);return!1},p=function(){e=c;c+=1;m.call(this);return!1},u=function(){var d=a.longPressDuration||200,f=!1,h=null,i=this,k=function(a){h=window.setInterval(function(){f&&a?(e=c,c+=a,m.call(i)):(window.clearInterval(h),h=null)},d)},j=function(){window.clearInterval(h);h=null;s.call(this);f=!0;k.call(this,-1)},n=function(){window.clearInterval(h);h=null;p.call(this);f=!0;k.call(this,1)},u=function(){f=!1};return{bindEvents:function(){avpw$(a.leftArrow).bind("mousedown",
j).bind("mouseup",u);avpw$(a.rightArrow).bind("mousedown",n).bind("mouseup",u)},unbindEvents:function(){avpw$(a.leftArrow).unbind("mousedown",j).unbind("mouseup",u);avpw$(a.rightArrow).unbind("mousedown",n).unbind("mouseup",u)}}}(),z=function(a,c,d){var e,f,h,i;a.length&&(a=a[0]);a.ontouchstart=function(a){if(a=AV.util.getTouch(a))e=a.pageX,h=a.pageY};a.ontouchmove=function(a){if(a=AV.util.getTouch(a))f=a.pageX,i=a.pageY;return!1};a.ontouchend=function(){var a=f-e,k=i-h;30<Math.abs(a)&&60>Math.abs(k)&&
(30<a?c():d());f=e=void 0}};this.shutdown=function(){if(1!==f){a.bindLongPress?u.unbindEvents():(avpw$(a.leftArrow).unbind("click"),avpw$(a.rightArrow).unbind("click"));var c=a.pageContainer;c.length&&(c=c[0]);c.ontouchstart=c.ontouchmove=c.ontouchend=null;d&&d.unbind("click")}a.pageContainer.html("");d&&a.pipContainer.html("")};this.changePage=m;this.pageLeft=s;this.pageRight=p;this.setCurrentPage=function(a){e=c;c=a};this.getCurrentPage=function(){return c};this.getPreviousPage=function(){return e};
this.getLastPage=function(){return f-1};this.getPageCount=function(){return f};this.setPageCount=function(a){f=a};a.pageContainer.html(function(){var c,d,e,i="";a.firstPageTemplate&&(i+=a.firstPageTemplate.apply(this,[a.firstPageContents]));for(d=c=0;d<f;d++){var k="";for(e=0;e<a.itemsPerPage&&c<a.itemCount;e++)k+=a.itemBuilder.apply(this,[c]),c++;i=a.pageTemplate?i+a.pageTemplate({panelHTML:k,panelWidth:a.pageWidth,panelClass:e===a.itemsPerPage?"avpw_scroll_page_complete":"avpw_scroll_page_incomplete"}):
i+k}a.lastPageTemplate&&(i+=a.lastPageTemplate.apply(this,[a.lastPageContents]));d=c=0;if(a.firstPageTemplate||a.lastPageTemplate)a.firstPageTemplate&&(a.firstPageWidth?c+=a.firstPageWidth*(a.itemsPerPage/a.pageWidth):f++),a.lastPageTemplate&&(a.lastPageWidth?c+=a.lastPageWidth*(a.itemsPerPage/a.pageWidth):f++),d=a.itemCount%a.itemsPerPage,c&&(0<d?d+c>a.itemsPerPage&&f++:f++,h=a.pageWidth/a.itemsPerPage-a.firstPageWidth%(a.pageWidth/a.itemsPerPage)|0);if(!a.pageTemplate&&a.fillRemainingSpace&&(c=
(a.itemCount+c)%a.itemsPerPage)){d=a.itemsPerPage-c;if(1===f&&a.centerContents){d=d/2|0;e="";for(c=0;c<d;c++)e+=a.fillRemainingSpace.apply(this);i=e+i}for(c=0;c<d;c++)i+=a.fillRemainingSpace.apply(this)}return i}());1===f?(avpw$(a.leftArrow).hide(),avpw$(a.rightArrow).hide(),a.centerContents&&(a.pageContainer.css("width","auto"),a.pageContainer.addClass("avpw_scroll_strip_centered"))):(avpw$(a.leftArrow).show(),avpw$(a.rightArrow).show(),a.pageContainer.removeClass("avpw_scroll_strip_centered"),a.pipContainer&&
a.pipTemplate&&(a.pipContainer.html(i()),d=a.pipContainer.find(".avpw_is_navpip"),k()));(function(){if(f!==1){if(a.bindLongPress)u.bindEvents();else{avpw$(a.leftArrow).bind("click",function(){return a.onPageLeft?a.onPageLeft.call(this):s.call(this)});avpw$(a.rightArrow).bind("click",function(){return a.onPageRight?a.onPageRight.call(this):p.call(this)})}z(a.pageContainer,s,p);d&&d.bind("click",function(a){a=avpw$(a.currentTarget).attr("pagenum");e=c;c=parseInt(a);m();return false})}})();return this};
AV.TransformStyle=function(a){var d=a||"";this.set=function(a){if(d)for(var e in a){var f=!1;d=d.replace(RegExp(e+"\\([^\\)]*"),function(){f=!0;return e+"("+a[e]});f||(d+=" "+e+"("+a[e]+")")}else for(e in a)d+=" "+e+"("+a[e]+")"};this.serialize=function(){return d};return this};"undefined"==typeof AV&&(AV={});window.Aviary=AV;AV.feather_loaded=!1;AV.feather_loading=!1;AV.build=AV.build||{version:"",imgrecvServer:"imgrecvserver.cgi",flashGatewayServer:"",imgrecvBase:"",inAppPurchaseFrameURL:"",imgtrackServer:"imgtrackserver.cgi",filterServer:"",jsonp_imgserver:"",featherTargetAnnounce:"feather_target_announce.html",proxyServer:"",feather_baseURL:"",feather_stickerURL:"",googleTracker:""};AV.defaultTools_legacy="sharpen whiten rotate flip resize crop redeye blemish colors saturation blur brightness contrast drawing text overlay".split(" ");
AV.defaultTools="enhance effects overlay orientation resize crop warmth brightness contrast saturation sharpness drawing text redeye whiten blemish".split(" ");
AV.defaultStickers=[[AV.build.feather_stickerURL+"400x400/sombrero.png",AV.build.feather_stickerURL+"100x100/sombrero.png",AV.build.feather_stickerURL+"1000x1000/sombrero.png"],[AV.build.feather_stickerURL+"400x400/helicopter.png",AV.build.feather_stickerURL+"100x100/helicopter.png",AV.build.feather_stickerURL+"1000x1000/helicopter.png"],[AV.build.feather_stickerURL+"400x400/crown.png",AV.build.feather_stickerURL+"100x100/crown.png",AV.build.feather_stickerURL+"1000x1000/crown.png"],[AV.build.feather_stickerURL+
"400x400/fez.png",AV.build.feather_stickerURL+"100x100/fez.png",AV.build.feather_stickerURL+"1000x1000/fez.png"],[AV.build.feather_stickerURL+"400x400/3d_glasses.png",AV.build.feather_stickerURL+"100x100/3d_glasses.png",AV.build.feather_stickerURL+"1000x1000/3d_glasses.png"],[AV.build.feather_stickerURL+"400x400/hipster_glasses.png",AV.build.feather_stickerURL+"100x100/hipster_glasses.png",AV.build.feather_stickerURL+"1000x1000/hipster_glasses.png"],[AV.build.feather_stickerURL+"400x400/disguise.png",
AV.build.feather_stickerURL+"100x100/disguise.png",AV.build.feather_stickerURL+"1000x1000/disguise.png"],[AV.build.feather_stickerURL+"400x400/aviators.png",AV.build.feather_stickerURL+"100x100/aviators.png",AV.build.feather_stickerURL+"1000x1000/aviators.png"],[AV.build.feather_stickerURL+"400x400/eyepatch.png",AV.build.feather_stickerURL+"100x100/eyepatch.png",AV.build.feather_stickerURL+"1000x1000/eyepatch.png"],[AV.build.feather_stickerURL+"400x400/bow_tie.png",AV.build.feather_stickerURL+"100x100/bow_tie.png",
AV.build.feather_stickerURL+"1000x1000/bow_tie.png"],[AV.build.feather_stickerURL+"400x400/tie.png",AV.build.feather_stickerURL+"100x100/tie.png",AV.build.feather_stickerURL+"1000x1000/tie.png"],[AV.build.feather_stickerURL+"400x400/pipe.png",AV.build.feather_stickerURL+"100x100/pipe.png",AV.build.feather_stickerURL+"1000x1000/pipe.png"],[AV.build.feather_stickerURL+"400x400/cigar.png",AV.build.feather_stickerURL+"100x100/cigar.png",AV.build.feather_stickerURL+"1000x1000/cigar.png"],[AV.build.feather_stickerURL+
"400x400/arrow.png",AV.build.feather_stickerURL+"100x100/arrow.png",AV.build.feather_stickerURL+"1000x1000/arrow.png"],[AV.build.feather_stickerURL+"400x400/green_bubble.png",AV.build.feather_stickerURL+"100x100/green_bubble.png",AV.build.feather_stickerURL+"1000x1000/green_bubble.png"],[AV.build.feather_stickerURL+"400x400/orange_bubble.png",AV.build.feather_stickerURL+"100x100/orange_bubble.png",AV.build.feather_stickerURL+"1000x1000/orange_bubble.png"],[AV.build.feather_stickerURL+"400x400/blue_bubble.png",
AV.build.feather_stickerURL+"100x100/blue_bubble.png",AV.build.feather_stickerURL+"1000x1000/blue_bubble.png"],[AV.build.feather_stickerURL+"400x400/pink_bubble.png",AV.build.feather_stickerURL+"100x100/pink_bubble.png",AV.build.feather_stickerURL+"1000x1000/pink_bubble.png"],[AV.build.feather_stickerURL+"400x400/star.png",AV.build.feather_stickerURL+"100x100/star.png",AV.build.feather_stickerURL+"1000x1000/star.png"],[AV.build.feather_stickerURL+"400x400/heart.png",AV.build.feather_stickerURL+"100x100/heart.png",
AV.build.feather_stickerURL+"1000x1000/heart.png"],[AV.build.feather_stickerURL+"400x400/red_arrow.png",AV.build.feather_stickerURL+"100x100/red_arrow.png",AV.build.feather_stickerURL+"1000x1000/red_arrow.png"],[AV.build.feather_stickerURL+"400x400/blue_arrow.png",AV.build.feather_stickerURL+"100x100/blue_arrow.png",AV.build.feather_stickerURL+"1000x1000/blue_arrow.png"],[AV.build.feather_stickerURL+"400x400/green_circle.png",AV.build.feather_stickerURL+"100x100/green_circle.png",AV.build.feather_stickerURL+
"1000x1000/green_circle.png"],[AV.build.feather_stickerURL+"400x400/orange_square.png",AV.build.feather_stickerURL+"100x100/orange_square.png",AV.build.feather_stickerURL+"1000x1000/orange_square.png"]];
(function(a){var d=function(a,c){c=c||{};return{theme:c.theme||a.Feather_Theme||"bluesky",minimumStyling:c.minimumStyling||!1,openType:c.openType||a.Feather_OpenType||"popup",layout:c.layout||"desktop_bluesky",language:c.language||a.Feather_Language||"en",forceFlash:c.forceFlash||a.Feather_ForceFlash,forceSupport:c.forceSupport||a.AV_Feather_ForceSupport,poweredByURL:c.poweredByURL||"http://www.aviary.com",giveFeedbackURL:c.giveFeedbackURL||"http://www.aviary.com/feature-requests",getWidgetURL:c.getWidgetURL||
"http://www.aviary.com",onLoad:c.onLoad||a.Feather_OnLoad,onReady:a.Feather_OnLaunchComplete,onClose:a.Feather_OnClose,onSave:a.Feather_OnSave,onSaveButtonClicked:a.Feather_OnSaveButtonClicked,onError:a.Feather_OnError,image:null,url:null,appendTo:null,noCloseButton:a.Feather_NoCloseButton,maxSize:a.Feather_MaxSize||a.Feather_MaxDisplaySize||800,maxEditSize:null,hiresMaxSize:1E4,hiresWidth:null,hiresHeight:null,tools:a.Feather_EditOptions&&"all"!==a.Feather_EditOptions&&"All"!==a.Feather_EditOptions&&
""!==a.Feather_EditOptions?a.Feather_EditOptions:AV.defaultTools_legacy,initTool:"",cropPresets:a.Feather_CropSizes||["","320x240","640x480","800x600","1280x1024","1600x1200","240x320","480x640","600x800","1024x1280","1200x1600","Original",["Square","1:1"],"Custom","3:2","3:5","4:3","4:5","4:6","5:7","8:10","16:9"],resizePresets:a.Feather_ResizeSizes||"320x240 640x480 800x600 1280x1024 1600x1200 240x320 480x640 600x800 1024x1280 1200x1600".split(" "),stickers:a.Feather_Stickers||AV.defaultStickers,
apiKey:a.Feather_APIKey,hiresUrl:a.Feather_HiResURL,postUrl:a.Feather_PostURL,postData:null,fileFormat:a.Feather_FileFormat||a.Feather_ContentType||"",jpgQuality:a.Feather_FileQuality||100,debug:!1,asyncSave:!0,signature:a.Feather_Signature||null,timestamp:a.Feather_Timestamp||null,useCustomFileExpiration:!1,allowInAppPurchase:!1}};AV.baseConfig=d(a);if("https:"==a.location.protocol||"chrome-extension:"==a.location.protocol){var c,e;for(e in AV.build)c=e.split("_SSL"),2===c.length&&AV.build[e]&&(c=
c[0],AV.build[c]=AV.build[e])}(a.Feather_Theme||a.Feather_OpenType||a.Feather_APIKey)&&a.setTimeout(function(){var c=new AV.Feather;a.aviaryeditor=function(e,i,k,j){AV.launchData=d(a,AV.baseConfig);e=AV.util.extend(AV.launchData,{image:e,url:i,postData:k,appendTo:j});c.launch(e)};a.aviaryeditor_close=c.close;a.aviaryeditor_relaunch=c.relaunch;a.aviaryeditor_activatetool=c.activateTool;a.aviarynewimage=c.replaceImage},0)})(window);
AV.getLocalizedString=function(a){try{var d=AV.lang[AV.launchData.language][a];void 0===d&&(d=a);return d}catch(c){}return a};Function.prototype.AV_bindInst=function(a){var d=this;return function(){return d.apply(a,arguments)}};
AV.util={getX:function(a){for(var d=0;null!=a;)d+=a.offsetLeft,a=a.offsetParent;return d},getY:function(a){for(var d=0;null!=a;)d+=a.offsetTop,a=a.offsetParent;return d},getTouch:function(a){a.originalEvent&&(a=a.originalEvent);return a.changedTouches&&1==a.changedTouches.length?a.changedTouches[0]:a.touches&&1==a.touches.length?a.touches[0]:!1},getOffset:function(a){function d(a){return a.currentStyle||h.getComputedStyle(a,"")}function c(a){var h=a.offsetParent,j;e+=parseInt(a.offsetLeft,10)||0;
f+=parseInt(a.offsetTop,10)||0;if(h){if(e-=parseInt(h.scrollLeft,10)||0,f-=parseInt(h.scrollTop,10)||0,1==h.nodeType){j=d(h);var n=h.localName,m=a.parentNode;"static"!=j.position?(e+=parseInt(j.borderLeftWidth,10)||0,f+=parseInt(j.borderTopWidth,10)||0,"TABLE"==n?(e+=parseInt(j.paddingLeft,10)||0,f+=parseInt(j.paddingTop,10)||0):"BODY"==n&&(j=d(a),e+=parseInt(j.marginLeft,10)||0,f+=parseInt(j.marginTop,10)||0)):"BODY"==n&&(e+=parseInt(j.borderLeftWidth,10)||0,f+=parseInt(j.borderTopWidth,10)||0);
for(;h!=m;)e-=parseInt(m.scrollLeft,10)||0,f-=parseInt(m.scrollTop,10)||0,m=m.parentNode;c(h)}}else{"BODY"==a.localName&&(j=d(a),e+=parseInt(j.borderLeftWidth,10)||0,f+=parseInt(j.borderTopWidth,10)||0,h=d(a.parentNode),e-=parseInt(h.paddingLeft,10)||0,f-=parseInt(h.paddingTop,10)||0);if(h=a.scrollLeft)e+=parseInt(h,10)||0;if(a=a.scrollTop)f+=parseInt(a,10)||0}}var e=0,f=0,h=a.ownerDocument.defaultView||window;a.length&&(a=a[0]);a&&c(a);return{left:e,top:f}},getScaledDims:function(a,d,c,e){var e=
e||c,f=a,h=d,i=a/d;if(a>c||d>e)a-c>i*(d-e)?(f=c,h=c*d/a+0.5|0):(f=e*i+0.5|0,h=e);return{width:f,height:h}},nextFrame:function(a){setTimeout(a,1)},getDomain:function(a,d){var c,e,f;c="http://"==a.substr(0,7)?7:"https://"==a.substr(0,8)?8:"ftp://"==a.substr(0,6)?6:0;e=a.indexOf("/",c);-1==e&&(e=a.length);d||(f=a.lastIndexOf(".",e),f=a.lastIndexOf(".",f-1),c=-1==f?c:f+1);return a.substring(c,e)},extend:function(){var a,d,c,e,f,h=arguments[0]||{},i=1,k=arguments.length,j=!1;"boolean"===typeof h&&(j=h,
h=arguments[1]||{},i=2);"object"!==typeof h&&!jQuery.isFunction(h)&&(h={});k===i&&(h=this,--i);for(;i<k;i++)if(null!=(a=arguments[i]))for(d in a)c=h[d],e=a[d],h!==e&&(j&&e&&(jQuery.isPlainObject(e)||(f=jQuery.isArray(e)))?(f?(f=!1,c=c&&jQuery.isArray(c)?c:[]):c=c&&jQuery.isPlainObject(c)?c:{},h[d]=jQuery.extend(j,c,e)):void 0!==e&&(h[d]=e));return h},loadFile:function(){var a,d,c,e,f=0,h;a=function(a){if(d){var c=function(a){(4==this.readyState||"complete"==this.readyState||"loaded"==this.readyState)&&
d(a)};"Microsoft Internet Explorer"==navigator.appName?a.onreadystatechange=c:a.onload=d}};return function(i,k,j){d=j;"js"==k?(c=document.createElement("script"),c.setAttribute("type","text/javascript"),a(c),c.setAttribute("src",i)):"css"==k?document.createStyleSheet?document.createStyleSheet(i,f++):(c=document.createElement("link"),c.setAttribute("rel","stylesheet"),c.setAttribute("type","text/css"),c.setAttribute("href",i)):"img"==k&&(c=document.createElement("img"),a(c),c.setAttribute("src",i));
c&&(e=e||document.getElementsByTagName("head")[0],"js"==k?e.appendChild(c):"css"==k&&(h=h||document.createDocumentFragment(),h.appendChild(c),e.insertBefore(c,void 0)));return c}}(),getImageElem:function(a){return"string"==typeof a?document.getElementById(a):a.length?a[0]:a},getImageId:function(a){return"string"==typeof a?a:a.id},imgOnLoad:function(a,d){var c=avpw$(a);c.load(d);(!0==c[0].complete||4==c[0].readyState||"complete"==c[0].readyState||"loaded"==c[0].readyState)&&c.trigger("load")},color_is_white:function(a){a=
a.toLowerCase();return"#fff"==a||"#ffffff"==a||"white"==a||"rgb(255, 255, 255)"==a},color_is_light:function(a){return"#fff"==a||"#ffffff"==a||"rgb(255, 255, 255)"==a},color_expand:function(a){4==a.length&&(r=a.charAt(1),g=a.charAt(2),b=a.charAt(3),a="#"+r+r+g+g+b+b);return a},color_to_rgb:function(a){var d,c;"#"==a.charAt(0)&&(a=AV.util.color_expand(a),d=parseInt(a.substr(1,2),16),c=parseInt(a.substr(3,2),16),a=parseInt(a.substr(5,2),16),a="rgb("+d+","+c+","+a+")");return a},rgb_to_color:function(a){var d,
c;return(c=a.match(/\s*rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/))?(a=parseInt(c[1]).toString(16),1==a.length&&(a="0"+a),d=parseInt(c[2]).toString(16),1==d.length&&(d="0"+d),c=parseInt(c[3]).toString(16),1==c.length&&(c="0"+c),"#"+a+d+c):a},color_to_int:function(a){a=AV.util.color_expand(a);a=AV.util.rgb_to_color(a);return parseInt(a.substr(1),16)}};
AV.errorNotify=function(a,d){var c={BAD_IMAGE:{code:1,message:"Unable to load image from `image` param provided."},UNSUPPORTED:{code:2,message:"Unable to detect Flash plugin or HTML canvas support. Cannot launch editor."},BAD_URL:{code:3,message:"Image at `url` param could not be accessed by Aviary service at "+(AV.featherUseFlash?AV.build.proxyServer:AV.build.imgrecvBase)+"."}}[a];"function"===typeof AV.launchData.onError&&(c.args=d,AV.launchData.onError(c))};
AV.injectControls=function(){var a,d;"popup"==AV.launchData.openType?(a="",d=AV.template[AV.launchData.layout].saveBlock()):(a=AV.template[AV.launchData.layout].saveBlock(),d="");if(AV.criticalLayoutStyles){var c=document.createElement("style");c.type="text/css";var e=document.createTextNode(AV.criticalLayoutStyles);c.styleSheet?c.styleSheet.cssText=e.nodeValue:c.appendChild(e);document.getElementsByTagName("head")[0].appendChild(c)}a=AV.template[AV.launchData.layout].controls({internalSaveBlock:a,
externalSaveBlock:d});d=document.createElement("div");d.id="avpw_holder";c="";AV.featherUseFlash&&(c="avpw_flash ");AV.msie&&(c+="avpw_ie"+AV.msie);c&&(d.className=c);(c=document.getElementsByTagName("body"))&&(c=c[0]);c||(c=document.documentElement);c.appendChild(d);d.innerHTML=a};
AV.setPopupPos=function(a){var d=AV.util.getX(a),c=AV.util.getY(a),a=d+(a.width<AV.launchData.maxSize?a.width:AV.launchData.maxSize)+15,d=document.getElementById("avpw_controls");d.style.position="absolute";d.style.left=a+"px";d.style.top=c+"px"};
AV.setLightboxPos=function(){var a;a="pageYOffset"in window?window.pageYOffset:(((t=document.documentElement)||(t=document.body.parentNode))&&"number"==typeof t.ScrollTop?t:document.body).scrollTop;document.getElementById("avpw_controls").style.top=a+30+"px"};AV.buildHiddenFrame=function(a,d,c){c||(c=AV.build.feather_baseURL+"blank.html");d||(d=a);return['<iframe width="1" height="1" style="position:absolute;left:-9999px;" ','id="'+a+'" name="'+d+'" src="'+c+'">',"</iframe>"].join("")};
AV.simpleXHRPost=function(a,d,c){function e(){c&&4===i.readyState&&c(i.responseXML)}function f(a){var c=[];avpw$.each(a,function(a,d){d&&c.push("Content-Disposition: form-data; "+('name="'+a+'"\r\n\r\n')+(d+"\r\n"))});a="--"+h+"\r\n";a+=c.join("--"+h+"\r\n");return a+="--"+h+"--\r\n"}var h="FEATHER-AJAX---"+(new Date).getTime(),i=new XMLHttpRequest;try{var k="multipart/form-data; charset=UTF-8; boundary="+h;i.open("POST",a,!0);i.setRequestHeader("Content-Type",k);i.onreadystatechange=e;var j=f(d);
i.send(j)}catch(n){return!1}return!0};
AV.Feather=function(a){var d=!1;if(a&&(a.apiVersion&&2===parseInt(a.apiVersion)&&(a.openType="aviary"),!a.tools||"all"===a.tools||"All"===a.tools||""===a.tools))d=!0;a=a||{};AV.launchData=AV.util.extend(AV.baseConfig,a);(function(){function a(c){var c=AV.build.feather_baseURL+"css/"+c,d=AV.launchData.theme;"mobile"==AV.launchData.openType||"aviary"==AV.launchData.openType?AV.util.loadFile(c+".css","css"):(AV.msie&&(8===AV.msie||7===AV.msie)?AV.util.loadFile(c+"_ie"+AV.msie+".css","css"):AV.featherUseFlash?
AV.util.loadFile(c+"_flash.css","css"):AV.util.loadFile(c+".css","css"),AV.util.loadFile(c+"-"+d+".css","css"))}AV.featherUseFlash=!AV.featherHtmlOk()&&AV.featherFlashOk();AV.launchData.language=AV.launchData.language.toLowerCase();"float"==AV.launchData.openType&&(AV.launchData.openType="popup");"integrated"==AV.launchData.openType&&(AV.launchData.openType="lightbox");"inline"==AV.launchData.openType&&(AV.launchData.openType="inject");AV.featherUseFlash&&"popup"==AV.launchData.openType&&(AV.launchData.openType=
"lightbox");d&&(AV.launchData.tools="aviary"===AV.launchData.openType?AV.defaultTools:AV.defaultTools_legacy,"mobile"==AV.launchData.openType&&AV.launchData.tools.unshift("effects"));if(!AV.feather_loaded&&!AV.feather_loading){AV.feather_loading=!0;var c="js/feathercontrols_desktop_bluesky.js";"mobile"==AV.launchData.openType?(c="js/feathercontrols_mobile.js",AV.launchData.layout="mobile_default"):"aviary"==AV.launchData.openType&&(c="js/feathercontrols_desktop.js",AV.launchData.layout="desktop");
"mobile"==AV.launchData.openType?a("feather_mobile"):"aviary"==AV.launchData.openType?AV.launchData.minimumStyling?a("feather_core"):a("feather_theme_aviary"):"popup"==AV.launchData.openType?a("feather"):a("feather_hd");"aviary"==AV.launchData.openType?AV.util.loadFile(AV.build.feather_baseURL+"images/aviary_atlas.png","img"):AV.util.loadFile(AV.build.feather_baseURL+"images/atlas-"+AV.launchData.theme+".png","img");AV.build.bundled?(AV.injectControls(),AV.util.nextFrame(AV.loadStageFinal)):AV.util.loadFile(AV.build.feather_baseURL+
c,"js",function(){AV.injectControls();AV.util.nextFrame(AV.loadStageFinal)})}})();var c=function(){if(AV.paintWidgetInstance)return!1;var a=AV.util.getImageElem(AV.launchData.image);"popup"==AV.launchData.openType?AV.setPopupPos(a):"lightbox"==AV.launchData.openType&&AV.setLightboxPos(a);AV.paintWidgetLauncher(a,AV.launchData.url)};this.launch=function(a){if(!AV.feather_loaded||AV.paintWidgetInstance)return!1;AV.launchData=a?AV.util.extend(AV.launchData,a):AV.launchData;if(!AV.launchData.image)return!1;
AV.launchData.image=AV.util.getImageElem(AV.launchData.image);if(AV.featherUseFlash)c();else{if(!AV.featherSupported())return AV.errorNotify("UNSUPPORTED"),!0;AV.util.nextFrame(c)}return!0};this.save=function(){return!AV.paintWidgetInstance?!1:AV.controlsWidgetInstance.save()};this.close=function(a){if(!AV.paintWidgetInstance)return!1;AV.paintWidgetCloser(a)};this.relaunch=function(){AV.isRelaunched=!0;if(AV.launchData)this.launch(AV.launchData);else return!1};this.activateTool=function(a){if(!AV.paintWidgetInstance)return!1;
AV.controlsWidgetInstance.setActiveTool(a)};this.replaceImage=function(a){if(AV.launchData)this.close(!0),AV.util.nextFrame(function(){AV.launchData.url=a;this.launch(AV.launchData)}.AV_bindInst(this));else return!1};this.updateConfig=function(a,c){if(AV.launchData&&a&&"string"===typeof a)AV.launchData[a]=c;else return!1};this.getIsDirty=function(){return AV.paintWidgetInstance?AV.paintWidgetInstance.dirty:!1};this.getImageData=function(a,c,d){var i=AV.controlsWidgetInstance;return AV.paintWidgetInstance&&
2===i.loaderPhase?(i.moduleNotify(i.curMode,"commit"),AV.paintWidgetInstance.exportImage(d,function(d){c&&AV.util.nextFrame(function(){AV.controlsWidget_onImageSaved(i.origURL)});a&&"function"===typeof a&&a.apply(this,[d])}),!0):!1};this.getActionList=function(){if(AV.paintWidgetInstance){var a=AV.controlsWidgetInstance;a.moduleNotify(a.curMode,"commit");return AV.paintWidgetInstance.actions.exportJSON(!0)}};this.disableControls=function(){AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,
"disableControls")};this.enableControls=function(){AV.controlsWidgetInstance.layoutNotify(AV.launchData.openType,"enableControls")};return this};
AV.setUpOstrich=function(){avpw_swfobject.embedSWF(AV.build.feather_baseURL+"ostrich/OstrichFeather.swf","avpw_OstrichFeather","1","1","10.0.0","ostrich/playerProductInstall.swf",{initializedCallback:"engineReady",allowDomains:"*",completeCallback:"AV.module_flashfilter_onFilterComplete"},{quality:"high",bgcolor:"#ffffff",allowscriptaccess:"always",allowfullscreen:"true",hasPriority:"true"},{id:"avpw_OstrichFeather",name:"avpw_OstrichFeather",align:"middle"})};
AV.loadStageFinal=function(){AV.feather_loaded=!0;if("function"===typeof AV.launchData.onLoad)AV.launchData.onLoad()};AV.featherSupported=function(){return AV.featherHtmlOk()||AV.featherFlashOk()||AV.launchData.forceSupport};AV.featherFlashOk=function(){return AV.launchData.forceFlash?!0:!AV.msie||7<=AV.msie};AV.featherHtmlOk=function(){if(AV.launchData.forceFlash)return!1;var a=!!document.createElement("canvas").getContext,d="function"===typeof window.postMessage;return a&&d};
AV.getFlashMovie=function(a){return window[a]||document[a]};AV.msie=function(){for(var a=3,d=document.createElement("div"),c=d.getElementsByTagName("i");d.innerHTML="<\!--[if gt IE "+ ++a+"]><i></i><![endif]--\>",c[0];);return 4<a?a:void 0}();AV.firefox=function(){var a;"Gecko"===navigator.product&&(a=navigator.userAgent.split("Firefox/")[1],a=parseInt(a,10));return a}();AV.PAGE_WIDTH=360;AV.setPageWidth=function(a){AV.PAGE_WIDTH=a};
AV.support=function(a){var d=a.navigator.userAgent,c=a.screen.width,a={"0":/Android/i,1:/webOS/i,2:/iPhone/i,3:/iPod/i,4:/BlackBerry/i,5:/iPad/i},e,f=0,h=0,i=0,k;for(k in a)d.match(a[k])&&(e=parseInt(k));d.match(/AppleWebKit/i)&&(f=1);0===e&&(h=1);1===h&&(d=d.match(/Android [0-9].[0-9]/).toString())&&(i=parseFloat(d.split("Android ")[1]));d={isAppleWebkit:function(){return f===1},isMobileWebkit:function(){return f===1&&c&&(c<=480||i>0&&i<=2.3)},isIPhoneOrIPod:function(){return e===2||e===3},isAndroid:function(){return h===
1},getAndroidVersion:function(){return i}};d.getVendorProperty=function(){var a={};return function(c){var d;if(!(d=a[c])){var e;a:{var f=document.createElement("div");d=c;var h=["webkit","ms","Moz","O"],i,k=f.style;if(k[d]!==void 0)e=d;else{d=d.charAt(0).toUpperCase()+d.slice(1);for(i=0;i<h.length;i++){f=h[i]+d;if(k[f]!==void 0){e=f;break a}}}}d=a[c]=e}return d}}();return d}(window);